### ISSUE TITLE
Placemark в Clusterer не отображаются

### ISSUE THREAD

**Issue by serzh-f** [gribnoysup/react-yandex-maps#101]
Привет всем.

Почему-то не отображается Placemark в Clusterer.
Сделано по примеру https://gribnoysup.github.io/react-yandex-maps/#/sandbox/clustering/clusterer-create , но удаляя <Clusterer> как родителя - булавки рендерятся. Добавляю <Clusterer> - ничего нет. 

В консоли ошибок нет. В чем может быть проблема? Спасибо :(

v2.2.1

**Comment by mmarkelov** [comment]
@serzh-f Очень странное поведение. Запуская пример локально - все работает как надо. В [песочнице](https://codesandbox.io/s/l7oqnz7mml) все падает, ставил более раннюю версию - все равно не работает. Я в замешательстве, но попытаюсь разобраться.

**Comment by serzh-f** [comment]
@mmarkelov Спасибо за ответ.
Да, действительно. Вчера проверил примеры локально - работают. Копирую этот же код в свой проект - не отображаются Placemark , если родитель Clusterer.

Посмотрю еще сегодня. Если пойму в чем проблема - отпишусь.

**Comment by mmarkelov** [comment]
@serzh-f Проблема со совместимостью с реактом версии 16.5.0, на 16.4.2 - все в порядке. Постараюсь выяснить что не так.

**Comment by gribnoysup** [comment]
@mmarkelov спасибо за оперативный фикс! @serzh-f @royroev @slonig @oledm должно работать в `react-yandex-maps@2.3.0`, можете проверить?

**Comment by oledm** [comment]
@gribnoysup Работает! Спасибо за фикс!

**Comment by serzh-f** [comment]
@gribnoysup Все отлично. Благодарю!
