### ISSUE TITLE
Как указать className у рута ?

### ISSUE THREAD

**Issue by js2me** [gribnoysup/react-yandex-maps#104]
Зашел в исходники компонента YMaps и там нет ничего про слово className

![image](https://user-images.githubusercontent.com/16340911/45718031-6480e680-bba4-11e8-8547-3fe727447974.png)

**Comment by js2me** [comment]
Как я понимаю, в ветке `next` уже есть это

**Comment by gribnoysup** [comment]
@js2me привет! Как ты правильно заменил это будет возможно только в следующем мажорном релизе. Если интересно попробовать как оно работает, то можно попробовать установить canary релиз

```sh
npm i --save react-yandex-maps@canary
```

Больших изменений в коде скорее всего не будет между `canary` и основным релизом, хотим закончить доки перед тем как выпускать
