### ISSUE TITLE
How to disable behavior

### ISSUE THREAD

**Issue by dideex** [gribnoysup/react-yandex-maps#105]
How to disable zoom with the mouse wheel?
Like:
`map.behaviors.disable('scrollZoom')`

**Comment by gribnoysup** [comment]
Hi @dideex! No easy way to do it, unfortunately, because of how Yandex.Maps API works. You can find a workaround in the related issue: https://github.com/gribnoysup/react-yandex-maps/issues/46#issuecomment-353273297 

You'll need to get access to the ref and turn it off manually:

```jsx
<Map instanceRef={ref => { ref && ref.behaviors.disable('scrollZoom'); }} />
```
