### ISSUE TITLE
Controls - управляющие элементы

### ISSUE THREAD

**Issue by koekaverna** [gribnoysup/react-yandex-maps#11]
Помогите разобраться с элементами управления. Как их корректно убирать/добавлять, менять их расположение и внешний вид.

Что конкретно нужно:
1) Задать положение и внешний вид  ZoomControl
2) Добавить одну кнопку (поверх карты), которая будет менять размер карты.

**Comment by gribnoysup** [comment]
Привет!

Во-первых хочу заметить, что `react-yandex-maps` это довольно тонкая обертка вокруг API Яндекс.Карт. Практически все поддерживаемые объектами из карт параметры и события можно прокинуть через `props` компонента на объект карт. У такого решения есть как свои плюсы, так и минусы (и это точно нужно будет подробнее описать в документации, я пока не успел это сделать)

Первый вопрос не так просто решить, но не невозможно. 

"Проблема" в том API, который предоставляет Яндекс для изменения layout'a их стандартных объектов. Он довольно сложный сам по себе и плохо интегрируется с React'ом (вот пример изменения layout'a для ZoomControl [в песочнице Я.Карт](https://tech.yandex.com/maps/jsbox/2.1/zoom_layout)), я все ещё думаю над удобным способом интегрировать это API с React'ом.

Вот пример того, как эта задача может быть решена:

```jsx
import React, { Component } from 'react';

import { YMaps, Map, ZoomControl } from 'react-yandex-maps'

function createZoomControlLayout(ymaps) {
  // Функция по созданию layout'a целиком взята из песочницы яндекс карт
  // https://tech.yandex.com/maps/jsbox/2.1/zoom_layout
  const ZoomLayout = ymaps.templateLayoutFactory.createClass(
    "<div>" +
      "<div id='zoom-in' class='btn'><i class='icon-plus'></i></div><br>" +
      "<div id='zoom-out' class='btn'><i class='icon-minus'></i></div>" +
    "</div>", {
      // ...
    }
  })

  return ZoomLayout
}

class App extends Component {

  state = { layout: null }

  handleApiAvaliable(ymaps) {
    const layout = createZoomControlLayout(ymaps)
    this.setState({ layout })
  }

  render() {
    const { layout } = this.state

    return (
      <YMaps
        // Когда апи яндекс карт станет доступен, мы создадим конструктор лейаута
        // для зума и положим его в стейт компонента
        onApiAvaliable={(ymaps) => this.handleApiAvaliable(ymaps)}
      >
        <Map
          state={{
            center: [0, 0],
            zoom: 3,
            controls: []
          }}
        >
          {/*
            Для того что бы правильно отрисовать наш новый зум,
            нам нужен доступ к апи яндекс карт, поэтому мы будем брать
            конструктор лейаута из стейта, если его нет, мы не будет рисовать
            зум на карте
          */}
          {layout &&
            <ZoomControl options={{ layout }} />}
        </Map>
      </YMaps>
    );
  }
}

export default App;
```

Важно понимать, что если при этом зум карты завязан на стейт приложения, такие кнопки могут рассинхронизировать стейт и карту, нужно дополнительно обрабатывать на `ZoomControl` событие `change` и синхронизировать его обратно со стейтом приложения, либо решать эту задачу с помощью компонентов `Button` и в событии `onClick` менять `zoom` в стейте приложения, как во втором примере.

Второе поведение довольно легко сделать. По сути все, что я делаю в коде ниже, это использую стандартные параметры из документации яндекс карт.

```jsx
import React, { Component } from 'react';

import { YMaps, Map, Button } from 'react-yandex-maps'

class App extends Component {

  state = {
    width: 300,
    height: 200,
    small: true
  }

  toggleState() {
    this.setState(prevState => prevState.small
      ? { width: '100%', height: '100%', small: false}
      : { width: 300, height: 200, small: true }
    )
  }

  render() {
    const { width, height } = this.state

    return (
      <YMaps>
        <Map
          width={width}
          height={height}
          state={{
            center: [0, 0],
            zoom: 3,
            // Отключаем дефолтные контролы яндекс карт
            controls: []
          }}
        >
          {/* Добавляем на карту нашу кастомную кнопку */}
          <Button
            // Все параметры из апи яндекс карт будут проброшены
            // на яндексовский объект при добавлении на карту
            // (это актуально не только для контролов)
            //
            // Описание параметров для кнопки:
            // https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/control.Button-docpage/#param-parameters
            data={{
              // Задаем лейбл кнопки и текст подсказки
              title: 'Toogle map size',
              content: 'Toggle'
            }}
            options={{
              // Меняем поведение кнопки с toggle на обычное
              selectOnClick: false
            }}
            // А дальше просто управляем стейтом компонента, как обычно.
            // Все события, которые поддерживаются объектами в яндекс картах,
            // поддерживаются в react-yandex-maps
            //
            // https://github.com/gribnoysup/react-yandex-maps#events
            onClick={() => this.toggleState()}
          />
        </Map>
      </YMaps>
    );
  }
}

export default App;
```

**Comment by gribnoysup** [comment]
Я закрою issue, если будут ещё вопросы, пиши

**Comment by koekaverna** [comment]
Добавил кнопки зум, но они не работают, в браузере в консоле нет ошибок, размер элементов управления нулевой, задал в инспекторе в браузере ширину, высоту и цвет фона, элементы появились, но на cliсk не реагируют.

Код скопировал здесь и из песочницы яндекс.
Единственное что изменил, вынес инициализацию стейта в конструктор, потому что иначе возникала ошибка.
```
  constructor() {
    super()
    this.state = { layout: null }
  }
```

**Comment by gribnoysup** [comment]
@koekaverna привет! Хочу на всякий случай уточнить пару вещей:

1) Стили в примере из "Песочницы" подключаются в файле `zoom_layout.html`, вот эта строчка:

```html
<link href="//yandex.st/bootstrap/2.2.2/css/bootstrap.min.css" rel="stylesheet">
```

2) В примере яндекса в функциях `build` и `clear` в конструкторе лейаута используется jQuery, если он не подключен, работать не будет, но и ошибок не будет. Я сделал полностью рабочее [демо на webpackbin](https://www.webpackbin.com/bins/-KgiHVEpQ8nDdcGL_PIb). Пиши, если еще будут вопросы

**Comment by koekaverna** [comment]
Да причина была в отсутствии стилей. Спасибо за ответ.
