### ISSUE TITLE
Placemark не работает

### ISSUE THREAD

**Issue by mirik999** [gribnoysup/react-yandex-maps#111]
Привет всем. 
Получаю ошибку когда пытаюсь выставить плейсмарк 

`const MyPlacemark = () => (
		<YMaps>
			<Map state={mapState} width="100%" height="380px">
				<Placemark geometry={{ coordinates: [40.38, 49.84] }} />
			</Map>
		</YMaps>
);`

Получаю сразу 2 ошибки в консоли: 

1. Uncaught TypeError: Cannot read property 'deserialize' of undefined
2. The above error occurred in the <r> component:

Где-то 4-5 месяцев назад на другом проекте подключал также яндекс мапс и все работало и работает по сей день идеально. Между проектами различается только версия реакта. На данный момент 16.5.2 а версия яндекс карты 3.0.2 . Есть решения ?

**Comment by gribnoysup** [comment]
Координаты для Placemark должны быть массивом: https://react-yandex-maps.now.sh/geo-objects/placemark#props
