### ISSUE TITLE
Add displayName property for components

### ISSUE THREAD

**Issue by VitalyKrenel** [gribnoysup/react-yandex-maps#113]
Hi!

I'm not sure why it's not working by default - maybe something is happening on my project's side.

All components from `react-yandex-maps` have the `Uknown` name. Take a look at screenshot of the React Developer Tools: 

![image](https://user-images.githubusercontent.com/17354709/47607899-ddd6e900-da2e-11e8-9dc2-10cb64f84a2c.png)

Right now I'm forced to patch those imported components but it's quite inconvinient.

```js
Map.displayName = 'Map';
Placemark.displayName = 'Placemark';
Polyline.displayName = 'Polyline';
```

I have to do this in order to use `enzyme` for testing my MapContainer component. I could stick with class names but those are changing sometimes through development phase.

Should I address this like a feature request or an issue?

**Comment by gribnoysup** [comment]
All components have `displayName` set up in non-production enviroment (`process.env.NODE_ENV !== 'production'`):

![Screenshot from the local dev build of the documentation showing components' display names](https://user-images.githubusercontent.com/5036933/47614375-51b0da00-da9f-11e8-83a3-048be4668a8d.png)
> Screenshot from the local dev build of the documentation

If you see `Unknown`, that means either your environment is set to `production` when the tests are running or you are importing special production bundles of the library which main purpose is to be used as a standalone production script imports thus should be as small as possible
