### ISSUE TITLE
how to change the view of the route panel for any mobile phone?

### ISSUE THREAD

**Issue by egor-a-trubnikov-panov** [gribnoysup/react-yandex-maps#117]
[screenshot 2018-11-07 at 14 08 17](https://user-images.githubusercontent.com/2979574/48121461-d61d0d00-e296-11e8-8f22-c09748bb1b90.png)

I want to have route panel view like this

**Comment by mmarkelov** [comment]
@egor-a-trubnikov-panov Hello! It will be nice if could provide some details about your issue

**Comment by gribnoysup** [comment]
Hi @egor-a-trubnikov-panov! Still not sure what are you trying to achieve. This library just gives you access to Yandex.Maps API through React components. Can you give us an example of how you can do it in Yandex.Maps (or how you would try to do it with just Yandex.Maps API) so we can figure out if this is possible with this library?

**Comment by gribnoysup** [comment]
Closed due to inactivity
