### ISSUE TITLE
need help map with geocode

### ISSUE THREAD

**Issue by horrrors** [gribnoysup/react-yandex-maps#118]
i need to make maps with geocoder and baloons, i spended two days and and i dont know how to finish this , can someone explain me, how i can do this with this react component?
this my code, but it seems like total shit, sorry

```jsx
class GeocoderPrinter extends React.Component {
      state = { geocoderPrint: null };
    
    componentDidMount() {
      this._isMounted = true;
  
      this.props.ymaps.geocode(this.props.geocode).then(geocode => {
          console.log(geocode)
        if (this._isMounted === true) {
          this.setState({
            geocoderPrint: geocode.geoObjects.metaData,
          });
        }
      });
    }
  
    componentWillUnmount() {
      this._isMounted = false;
    }
  
    render() {
      return this.state.geocoderPrint == null ? (
        <p>Loading route...</p>
      ) : (
        <p>This route is {this.state.geocoderPrint} long</p>
      );
    }
  }
  
  const ConnectedGeocoder = withYMaps(GeocoderPrinter, true, ['geocode']);

export default class MyTasks extends Component {
    render() {
        return (
            <YMaps>
                {/* <Map 
                width={600}
                height={600}
                defaultState={{ center: [55.75, 37.57], zoom: 9}} /> */}
                <Map width="100%" defaultState={{ center: [45, 41], zoom: 9 }}>
                    <ConnectedGeocoder geocode={['Moscow']} />
                                    <GeolocationControl options={{ float: 'left' }} />
                                    <RouteButton options={{ float: 'right' }} />
                                    <Placemark
                                             modules={['geoObject.addon.balloon']}
                                            defaultGeometry={[44.997655,41.129644]} 
                                            properties={{balloonContent:'my placemark'}}/>
                                </Map>
            </YMaps>
        );
    }
}
```

**Comment by gribnoysup** [comment]
Hi @horrrors! Can you explain what are you trying to achieve with this code? What is the behaviour that you expect?

**Comment by horrrors** [comment]
Здравствуйте, мне необходимо с помощью geocode переводить строковое представление адреса в координатную и добавлять метки на карту, однако никак не могу это реализовать, а все подсказки, имевшие под собой некоторую часть кода - устарели вместе с версией :)

**Comment by gribnoysup** [comment]
Набросал два варианта решения такой задачи: 

1. `Geocoder` -  компонент, который ищет координаты и вызывает onChange коллбэк, когда получает их, в дальнейшем приложение используется этот коллбэк что бы императивно добавить коориданы на карту используя ref на обьект карты из АПИ Яндекс.Карт

2. `GeocoderWithRenderProp` - компонент, который использует [render prop](https://reactjs.org/docs/render-props.html) паттерн, ожидает что его children prop будет функцией и во время рендера вызывает эту функцию со своим стейтом, куда сохраняются найденные координаты

Второй вариант более декларативный, так как не надо вручную добавлять объекты на карту, позволяет избежать использования дополнительных функций и ссылок на объект карты и дает больше контроля над тем, как именно отрендерить эти координаты

https://codesandbox.io/s/7k2rlrko81

Если это отвечает на вопрос, закройте, пожалуйста, issue
