### ISSUE TITLE
How to get templateLayoutFactory

### ISSUE THREAD

**Issue by ShiiRochi** [gribnoysup/react-yandex-maps#119]
I need to create markers with custom layout. In issue #27 contextTypes were used to receive ymaps, however after the definiton of the same contextTypes structure I found out that ymaps in the context was empty. The second way I tried was to access ymaps with HOC. And again, incoming ymaps from that HOC hasn't templateLayoutFactory. Maybe I should somehow tell withYMaps to load that module, if it is a module and If not, then how can I access that thing?

**Comment by ShiiRochi** [comment]
Sorry, it was realy some kind of a dumb question after all. 
Prefer to leave this issue here in case someone else will occur the same problem. 
The main issue is that **templateLayoutFactory** is realy a module itself and it is not loaded by default. It you want it, then just add it it modules, that should be loaded or load full package, or if you need it on-demand, then just wrap your component in ```withYMaps```, set second param true (component will wait until API is loaded) and as third param is an array, to which you should just add:
```
templateLayoutFactrory
```
to the modules list, that should be loaded.

**Comment by gribnoysup** [comment]
There is also an example of how to do a HOC for `templateLayotFactory` in migration guide:

https://react-yandex-maps.now.sh/migration-guide#onapiavaliable-is-removed-from-the-library

It is kinda confusing, I know. We will move a bunch of those to FAQ at some point

**Comment by ShiiRochi** [comment]
@gribnoysup, thanks
