### ISSUE TITLE
How to run startFraming in polygon?

### ISSUE THREAD

**Issue by MadnessRussian** [gribnoysup/react-yandex-maps#122]
i need to do this https://tech.yandex.ru/maps/jsbox/2.1/rectangle_editor
my polygon:
`<Polygon
              geometry={[
                [[30, 40],
                  [30, 50],
                  [40, 50],
                  [40, 40],
                  [30, 40]],
              ]}
              options={{
                fillColor: '#00FF00',
                strokeColor: '#0000FF',
                opacity: 0.5,
                strokeWidth: 5,
                strokeStyle: 'shortdash',
              }}
              startFraming
              onLoad={this.onLoad}
            />` 
in <Map> component

**Comment by MadnessRussian** [comment]
@mmarkelov Thanks! that work fine!

**Comment by MadnessRussian** [comment]
Hey! how i may to run a methods of polygon from https://tech.yandex.ru/maps/doc/archive/jsapi/2.0/ref/reference/geometry.Polygon-docpage/
contains and other?

**Comment by mmarkelov** [comment]
@MadnessRussian I update sandbox. You need to use **geometry** property of **ref**. Also you can check it [here](https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Polygon-docpage/#field_detail__geometry) and [here](https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/geometry.Polygon-docpage/)

**Comment by MadnessRussian** [comment]
Its good solution 👍 
my last question:
i need to get all Points in this polygon.

i try that by:

`var objects = ymaps.geoQuery(myGeoObjects); // its good
var objectsInside = objects.searchInside(myPolygon); // myPolygon from ref
`
but i have error :
`typeError: o.getType is not a function`

what the object i must send to searchInside ?

**Comment by mmarkelov** [comment]
@MadnessRussian youp. I completely ruin my sandbox. ( Could you give some info about what do you want to achieve and also it will be nice if could give link on your example

**Comment by MadnessRussian** [comment]
@mmarkelov i neet get all points from polygon, everytime when he move and resize.
my example : https://codesandbox.io/s/vnjo0n8jml
in onDrag i need get points and id's of this points

**Comment by mmarkelov** [comment]
@MadnessRussian just stack with it - something is near of [it](https://codesandbox.io/s/pk0vz7rw4m), I just haven't got any experience with Ymaps in such cases, so I have troubles with it(

**Comment by MadnessRussian** [comment]
@mmarkelov thank you very much for your help!
but i have problems with get all geoObjects from ObjectManagers.
Placemark - is simple geoObject in map, i may easy get it all
GeoObject is special structrue, not support geoQuery and can't give me all geoObjects :( 
without this method searchInside not work.
example in codesandbox on last post.

It's problem yandex api. not this lib :) Thanks!

**Comment by gribnoysup** [comment]
Closed due to inactivity
