### ISSUE TITLE
get current version of yandex Maps API

### ISSUE THREAD

**Issue by mrgreenward** [gribnoysup/react-yandex-maps#123]
Hi, i  want to get current version of yandex API. I set it in query,but script load  always 2.1.
<img width="578" alt="2018-12-11 11 50 09" src="https://user-images.githubusercontent.com/17414015/49788924-b23c6380-fd3b-11e8-9544-e5a7f75e6e27.png">
<img width="464" alt="2018-12-11 11 50 25" src="https://user-images.githubusercontent.com/17414015/49788925-b23c6380-fd3b-11e8-83f2-18404a9122b5.png">

**Comment by mmarkelov** [comment]
@mrgreenward You need to set version in **version** property, like so:
```javascript
<YMaps version="2.1.72"/>
```

**Comment by mrgreenward** [comment]
thanks!
