### ISSUE TITLE
Uncaught TypeError: Constructor Map requires 'new'

### ISSUE THREAD

**Issue by tayagorbunova** [gribnoysup/react-yandex-maps#125]
Привет! Установила библиотеку, повторила в своем проекте код в точности, как в начальном примере документации. В итоге на компоненте, в котором используется` <Map />` падает ошибка - `Uncaught TypeError: Constructor Map requires 'new'`.

**Comment by mmarkelov** [comment]
@tayagorbunova привет! Можешь сделать репро к примеру на [codesandbox](https://codesandbox.io). Так трудно сказать, в чем проблема
Повторил первый пример из доки - все хорошо:
[![Edit 50m9o27v9l](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50m9o27v9l)

**Comment by kombuchamp** [comment]
@tayagorbunova Map импортирован из 'react-yandex-maps'?

**Comment by vsed** [comment]
@kombuchamp была та же проблема при попытке встроить карту в Gatsby проект. Импорт Map помог, благодарю!
