### ISSUE TITLE
События к ObjectManager

### ISSUE THREAD

**Issue by jonikss** [gribnoysup/react-yandex-maps#13]
Не совсем понятно как реализовать с помощью этой библиотеки вот такой пример https://tech.yandex.com/maps/jsbox/2.1/object_manager_events
т.е. привязку событий?

**Comment by jonikss** [comment]
Похоже разобрался, использовал что то типа такого:

import React, {Component} from 'react';
import { YMaps, Map, ObjectManager } from 'react-yandex-maps';

import data from '../json/data.json';

const mapState = { center: [55.76, 37.64], zoom: 10 };

export default class MyMap extends Component {    
    onObjectEvent = (e) => {
        var objectId = e.get('objectId');
        if (e.get('type') === 'mouseenter') {
            // The setObjectOptions method allows you to set object options "on the fly".
            this.managerInstance.objects.setObjectOptions(objectId, {
                preset: 'islands#yellowIcon'
            });
        } else {
            this.managerInstance.objects.setObjectOptions(objectId, {
                preset: 'islands#blueIcon'
            });
        }
    }
   
    render() {
        return (
            <YMaps>
                <Map state={mapState} width={'100%'} height={'500'}>
                    <ObjectManager
                        instanceRef={(obj) => this.managerInstance = obj}
                        options={{
                          clusterize: true,
                          gridSize: 32,
                        }}
                        objects={{
                          preset: 'islands#greenDotIcon',
                        }}
                        clusters={{
                          preset: 'islands#greenClusterIcons',
                        }}
                        features={data.features}
                        events = {{onMouseEnter: this.onObjectEvent, onMouseLeave: this.onObjectEvent}}

                    />
                </Map>
            </YMaps>
        );
    }
}

**Comment by gribnoysup** [comment]
@jonikss привет! Тот способ, который ты нашел, это скорее эксплуатация немного кривого куска кода, который отвечает за события в библиотеке (я скорее всего это исправлю и твой вариант перестанет работать)

События можно прокидывать [прямо на React-элемент](https://github.com/gribnoysup/react-yandex-maps#events). Выглядеть будет вот так:

```jsx
<ObjectManager
    // ... other props

    onMouseEnter={this.onObjectEvent}
    onMouseLeave={this.onObjectEvent}
/>
```

Единственная существенная разница с примером из песочницы в том, что цвет на кластерах не меняется :( Быстро решение будет забиндить события прямо на `this.managerInstance` так же, как это делается в примере в "Песочнице"

**Comment by jonikss** [comment]
@gribnoysup Ок. Благодарю!
