### ISSUE TITLE
Получение информации о текущем элементе по клику на Placemark

### ISSUE THREAD

**Issue by lashevskiy** [gribnoysup/react-yandex-maps#130]
Можно ли каким-нибудь образом получать информацию об объекте при клике (именно при раскрытии baloon-а) на его Placemark? 
Хочется над компонентой-картой сверху отрисовывать другой компонент с информацией об объекте, чей balloon Placemark открыт на карте. Не удается добиться данного результата(

**Comment by lashevskiy** [comment]
Удалось получать информацию о точке (прохожусь мапой по массиву), при этом положив данные точки в properties (возможно можно сделать это правильнее?)
<Placemark instanceRef={ref => { ref && ref.events.add('balloonopen', (e) => { console.log('Кликнули по точке', e.originalEvent.currentTarget.properties._data.item); }); }} properties={{tem: item,}}/>

При этом возникла другая проблема: т к я использую Clusterer, то при объединении объектов в кластер не происходит данного события, при этом открывается общий список объектов которые находятся в этом кластере. В итоге не понятно как решать возникшую задачу

**Comment by slide13** [comment]
@lashevskiy, а откуда вы данные для placemark берете? Из какого-то массива же с точками, наверное, в state или redux store?
Вот и передавайте в onClick id этой точки, index в массиве или что у вас там является ее идентификатором, да хоть все данные точки в виде объекта передавайте. В этом случае ref и не нужен.

> При этом возникла другая проблема: т к я использую Clusterer, то при объединении объектов в кластер не происходит данного события, при этом открывается общий список объектов которые находятся в этом кластере. В итоге не понятно как решать возникшую задачу

У clusterer есть опция clusterOpenBalloonOnClick, если ее поставить в false балун кластера, содержащий все входящие в него точки не появится. У самого clusterer тоже есть событие onClick, внутри которого можно найти все входящие в кластер точки, но т.к. в кластер собирается несколько точек, информацию по какой именно вы собираетесь отображать? В общем, немного не понимаю финальную цель, что должно получиться.

**Comment by lashevskiy** [comment]
@slide13 ,

> @lashevskiy, а откуда вы данные для placemark берете? Из какого-то массива же с точками, наверное, в state или redux store?
> Вот и передавайте в onClick id этой точки, index в массиве или что у вас там является ее идентификатором, да хоть все данные точки в виде объекта передавайте. В этом случае ref и не нужен.
> 
> > При этом возникла другая проблема: т к я использую Clusterer, то при объединении объектов в кластер не происходит данного события, при этом открывается общий список объектов которые находятся в этом кластере. В итоге не понятно как решать возникшую задачу
> 
> У clusterer есть опция clusterOpenBalloonOnClick, если ее поставить в false, то балун кластера, содержащий все входящие в него точки, не появится. У самого clusterer тоже есть событие onClick, внутри которого можно найти все входящие в кластер точки, но т.к. в кластер собирается несколько точек, информацию по какой именно вы собираетесь отображать? В общем, немного не понимаю финальную цель, что должно получиться именно в этом случае.

По первому вопросу действительно удалось просто прокинуть объект напрямую в onClick.
Правда в итоге пока это не решает необходимую задачу. 

Вообще хочется сделать так: на карте отображаю много объектов (с кластеризацией). По каждому объекту можно кликнуть и увидеть краткую информацию в балуне, а также можно раскрыть детальную информацию (перейти на новую страницу в которую отправить инфу по нужному объекту). 
Проблема именно с отображением детальной информации. Наверное, в балуне должна быть кнопка по нажатию на которую должен выполняться  необходимый js, но сделать этого в рамках библиотеки не удалось. Можно ли реализовать такое?

**Comment by slide13** [comment]
@lashevskiy ,
У Placemark есть свойство balloonContentBody, в него можно передавать обычный html, для того, чтобы сделать кастомный балун.

**Comment by lashevskiy** [comment]
@slide13 , попробовал сделать содержимое и привязать обработку нажатия (функция в react компоненте)
balloonContentFooter: '<input type="button" onclick="this.handleClick()" value="Считать кроликов!"/>' 
Но на выходе имею ошибку:
(index):1 Uncaught TypeError: this.handleClick is not a function at HTMLInputElement.onclick ((index):1)
Также не удается прокинуть и item в метод

**Comment by mmarkelov** [comment]
@lashevskiy что-то такое не подойдет?
[![Edit 65r1819n](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/65r1819n)

**Comment by lashevskiy** [comment]
> @lashevskiy что-то такое не подойдет?
> [![Edit 65r1819n](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/65r1819n)

Здесь как раз есть проблема о которой говорил ранее - когда несколько точек имеют одинаковые координаты и мы не можем отобразить инфу о точках, входящих в кластер, по отдельности. 

Подготовил пример, который хотелось бы чтобы работал, но видимо что-то упускаю, либо же так все-таки сделать и нельзя
https://codesandbox.io/s/xlqwjw43wp
В футере балуна нажать на "Считать кроликов", вот здесь бы хотелось меть возможность вызвать метод компонента  параметром передать текущий объект.

**Comment by slide13** [comment]
@lashevskiy , нельзя просто так взять и вызвать в html функцию из реакт компонента
По идее можно через ref как-нибудь, но в голову ничего не лезет сейчас, да и времени сейчас нет.
Вот хак через глобальную переменную:

[![Edit react-yandex-maps issue #130](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xjw8xyx26w)

**Comment by mmarkelov** [comment]
@lashevskiy Согласен с @slide13 - можно поизвращаться, но это будет супер костыльно. Есть вариант использовать свой компонент вместо балуна и рендерить его в зависимости от координат, но это тоже будет не супер оптимальное решение.

**Comment by lashevskiy** [comment]
Эх, вроде бы простой кейс казалось - отобразить инфу в другом месте о выбранном на карте объекте, а получается без костылей и не сделать все-таки?

**Comment by mmarkelov** [comment]
@lashevskiy к сожалению, да - балун Яндекса не поддерживает Реакт, поэтому для такого кейса нужно извращаться. Можешь посмотреть https://github.com/gribnoysup/react-yandex-maps/issues/23 - где уже поднимался данный вопрос, также есть https://github.com/gribnoysup/react-yandex-maps/issues/27 - возможно что-то из этого тебе поможет

**Comment by mmarkelov** [comment]
@lashevskiy @slide13 @gribnoysup Я очень сильно накостылил - так что пока это пробный вариант того, как можно использовать компонент реакта внутри **BalloonContentLayout**
Подумаю о том, как и что можно еще с этим сделать:
https://codesandbox.io/s/m584w8n7o9

**Comment by lashevskiy** [comment]
@mmarkelov ого, зато работает, правда кроме варианта, когда несколько объектов имеют одинаковые координаты и объединяются. что как раз и нужно 
подготовил пример: 
[](https://codesandbox.io/s/j34p4yv97w)

**Comment by lashevskiy** [comment]
Начал делать, но не удается пробросить данные в лейаут кластера по аналогии с поинтером, возможно для этого тоже есть какое-то свойство в библиотеке? 
https://codesandbox.io/s/rw1mw808ym

**Comment by mmarkelov** [comment]
@lashevskiy Это еще более специфичный кейс, нужно как-то слушать изменения активного элемента в Кластере, у меня, к сожалению нет ни малейших идей как это сделать. Постараюсь придумать как это можно будет сделать
https://codesandbox.io/s/5vvjpl5yml

**Comment by mmarkelov** [comment]
@lashevskiy да, это настолько дикий костыль) Я особо не имел опыта с Кластером с настолько специфичным кейсом) Попытки найти решение, которое можно было бы подружить с либой я пока не нашел, постараюсь еще посмотреть что можно придумать

**Comment by mmarkelov** [comment]
@lashevskiy Пожалуй, это максимум из того, что я смогу выжать - лютые танцы с бубнами.
https://codesandbox.io/s/5vvjpl5yml

**Comment by gribnoysup** [comment]
Как уже несколько раз заметили выше, рендерить React в Balloon нетривиальная задача в целом,  [yandex-maps-react](https://github.com/effrenus/yandex-map-react) умеет, но мне не очень нравится насколько негибкая там имплементация. В вашем кейсе это еще усложняется тем, что это не всегда балун, иногда это кластер и тут вам даже рендер в балун никак не поможет.

> Вообще хочется сделать так: на карте отображаю много объектов (с кластеризацией). По каждому объекту можно кликнуть и увидеть краткую информацию в балуне, а также можно раскрыть детальную информацию (перейти на новую страницу в которую отправить инфу по нужному объекту).
> 
> Проблема именно с отображением детальной информации. Наверное, в балуне должна быть кнопка по нажатию на которую должен выполняться необходимый js

Мне кажется это не совсем то, что было в первом сообщении, но в процитированном комментария написано что это результат который вам нужен в итоге, так что я буду рассматривать решение именно для этого описания. 

Если вам надо для получения подробной информации перейти по ссылке, добавьте ссылку в `balloonContent` и реагируйте на нее.

В примене ниже я использую ObjectManager потому что в целом он более производительный чем "ручные" кластеры. В "кратком описании" каждой точки есть ссылка, которая меняет хэш в URL, что заставляет появится текст на экране под картой, это так же может быть ссылка на другую страницу, не обязательно хэш. Имплементация довольно наивная, но думаю идея должна быть понятна: роут в этом случае выступает как ваш способ сообщить об изменении стейта. Бонусом вы получаете возможность шарить ссылки на описание конкретного элемента

[![Edit 4xjykz2039](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4xjykz2039)

**Comment by lashevskiy** [comment]
@gribnoysup дело в том, что вариант просто ссылкой не совсем подходит, поскольку в рамках приложения по нажатию на "Подробнее" (например), необходимо, чтобы вызвались некоторые экшены, изменился стейт, и уже далее был выполнен переход на другой компонент, причем не как открытие по ссылке, а за счет внутреннего стейта (не используется роутинг в общем).

**Comment by slide13** [comment]
Как мне кажется, это все таки не совсем обычный кейс, поэтому тут можно сделать проще, через глобальную функцию (краткий пример я приводил ранее), которая будет апдейтить стейт и указывать у какой точки нажата кнопка "Подробнее". А далее уже что душе угодно - хоть из массива точек подробности показываем, хоть в componentDidUpdate экшен диспатчим, главное проверку правильно сделать, чтобы в бесконечный ререндер не ушло.
Собственно, вот более подробно:

[![Edit react-yandex-maps issue #130](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xvmy7qyy5q)

**Comment by lashevskiy** [comment]
@slide13 отличный вариант, это решило мою проблему, спасибо!

**Comment by mmarkelov** [comment]
Возможно кому-нибудь пригодится - вариант поддержки **React** компонентов для  **layoutFactory**. 
https://github.com/mmarkelov/react-yandex-maps-layout
