### ISSUE TITLE
Многократные перерисовки при получении координат GeoObject при его перетаскивании по карте

### ISSUE THREAD

**Issue by lashevskiy** [gribnoysup/react-yandex-maps#131]
Сделал пример: https://codesandbox.io/s/x9q6y0lv8q

Создаю перетаскиваемый GeoObject и вешаю на него событие окончания перетаскивания 
`<GeoObject instanceRef={ref => ref && this.setCenterForSearch(ref)} />`
где
```javascript
  setCenterForSearch = ref => {
    ref.events.add("dragend", this.callback);
  };

  callback = e => {
    let coords = e.originalEvent.target.geometry._coordinates;
    let res = [coords[0], coords[1]];
    this.setState({ locationCenterToFind: res });
  };
```
В итоге при каждом перетаскивании объекта происходит увеличение количества перерисовок: 2, 4, 8, 16 и т д раз при каждом новом изменении позиции. 
Как можно ли избежать данную ситуацию ? Поскольку если перетащить объект раз 10, то карта начинает подтормаживать сильно и в итоге все висит

**Comment by slide13** [comment]
@lashevskiy , здесь не нужен ref.
Достаточно добавить событие onDragEnd для геообъекта, пример:

```
onDragEnd={
                event => {
                  console.log(event.originalEvent.target.geometry.getCoordinates())
                }}
```
