### ISSUE TITLE
isOpen undefined  when provider equal  'yandex#search'

### ISSUE THREAD

**Issue by FriOne** [gribnoysup/react-yandex-maps#133]
When search provider is used you can see this error in the console.

> Uncaught TypeError: Cannot read property 'isOpen' of undefined
>     at u.show (combine.js?callback_prefix=__jsonp_react-yandex-maps-sandbox_combine&mode=release&flags=&load=81852_8V!8*s*p*m*n:e,O,v*o0N1l*l8_,P:Z1x!63N9d8J9a9b8I9c8Z:18)

So you can't see resuls in this case. Is it a problem with Yandex Maps itself or the library?

**Comment by mmarkelov** [comment]
@FriOne Could you provide some representation? This is very difficult to understand something without code

**Comment by FriOne** [comment]
Put this part of code [here](https://react-yandex-maps.now.sh/controls/search-control):
```
    <SearchControl
        options={{
          provider: 'yandex#search'
        }}
      />
```

**Comment by mmarkelov** [comment]
@FriOne seems like it is yandex map bug itself

**Comment by FriOne** [comment]
@mmarkelov seems like this is not the maps issue. Because [this](https://jsfiddle.net/dhf9cb0o/) wokrs

**Comment by mmarkelov** [comment]
@FriOne youp, I'll check it out.

**Comment by mmarkelov** [comment]
@FriOne You need to load full library to do this:
```javascript
      <YMaps query={{ load: "package.full" }}>
        <Map defaultState={mapState}>
          <SearchControl
            options={{
              provider: "yandex#search"
            }}
          />
        </Map>
      </YMaps>
```
https://codesandbox.io/s/0038row98l

**Comment by FriOne** [comment]
@mmarkelov this will bump all elements to the map. But search works)
Guess we need to add a module that id required for searching
![image](https://user-images.githubusercontent.com/5888410/52164014-77dcba80-271d-11e9-8fb9-8d1bd658ecfc.png)

**Comment by mmarkelov** [comment]
@FriOne yes, this is true, I just don’t know which modules are needed.

**Comment by FriOne** [comment]
Found it, it is `geoObject.addon.balloon`& Thanks for help!
