### ISSUE TITLE
Информация про withYMaps 

### ISSUE THREAD

**Issue by VladimirLHk** [gribnoysup/react-yandex-maps#135]
Здравствуйте!
Подскажите, пожалуйста, где в документации можно поподробнее почитать про withYMaps?
В частности, что означает второй параметр, который во всех примерах true?
А что будет если поставить false?

**Comment by mmarkelov** [comment]
@VladimirLHk можно почитать [здесь] (https://react-yandex-maps.now.sh/provider-consumer/with-ymaps-hoc)

**Comment by VladimirLHk** [comment]
Спасибо! Не дочитал :)
