### ISSUE TITLE
Automatic display of information

### ISSUE THREAD

**Issue by KonstantinZhukovskij** [gribnoysup/react-yandex-maps#139]
Add possibly, automatic display of information, without clicking on the label. And use the buttons inside Placemark. 

[Example automatic display](https://imgur.com/a/HTJvGcG)
[Example Placemark buttons](https://imgur.com/a/H1CntwD)

**Comment by mmarkelov** [comment]
@KonstantinZhukovskij you can use **instanceRef** and **balloon.open()** to open balloon, 
and **balloonContent** to add buttons to your balloon
```javascript
              <Placemark
                instanceRef={ref => ref && ref.balloon.open()}
                key={index}
                geometry={point}
                properties={{
                  item: index,
                  balloonContentHeader: "Заголовок элемента X",
                  balloonContentBody: "Тело элемента",
                  balloonContentFooter:
                    "<button>One</button><br/><button>Two</button>"
                }}
              />
```
https://codesandbox.io/s/8lm3rkj712

**Comment by KonstantinZhukovskij** [comment]
When I use the switch to another city with `<ListBox>   <ListBoxItem/>  </ListBox>` an open balloon does not allow me to switch, but always returns me to the first place.

**Comment by gribnoysup** [comment]
Please open a new issue if the topic is different
