### ISSUE TITLE
dosen't work in ie11

### ISSUE THREAD

**Issue by erisnuts** [gribnoysup/react-yandex-maps#140]
![photo_2019-02-26_00-57-48](https://user-images.githubusercontent.com/3906376/53364894-a424d900-3961-11e9-9c8f-c0f0726b6adf.jpg)

**Comment by mmarkelov** [comment]
@erisnuts Seems like you need polyfill for Promise, unfortunately I can't reproduce your issue.
You can try this [polyfill](https://github.com/taylorhakes/promise-polyfill), hope it will help

**Comment by gribnoysup** [comment]
As @mmarkelov said, polyfills are not included. It's definitely not mentioned in the docs, sorry for that! We will add something to the docs about the polyfills and browser support
