### ISSUE TITLE
new ymaps.Layer

### ISSUE THREAD

**Issue by mrgreenward** [gribnoysup/react-yandex-maps#142]
Привет! Подскажите плиз, есть ли возможность добавления нового слоя на карту?
В документации API карт показано так: 
```
map.layers.add(new ymaps.Layer(
'http://tile.openstreetmap.org/%z/%x/%y.png', {
    projection: ymaps.projection.sphericalMercator
}));
map.copyright
```
Я добавляю в <Map>:
` instanceRef={ref => (this.map = ref)}`
затем в  методе добавляю:
```
const { ymaps } = this.state;
const currentLayer = new ymaps.Layer(new ymaps.Layer(
'http://tile.openstreetmap.org/%z/%x/%y.png', {
    projection: ymaps.projection.sphericalMercator
})
map.layers.add(currentLayer);
```
но консоль пишет:
`index.jsx:115 Uncaught (in promise) TypeError: ymaps.Layer is not a constructor`

**Comment by mrgreenward** [comment]
Все разобрался, если у кого подобная проблема будет,  нужно добавить в <YMaps>
```
 query={{
                 load: "package.full"
            }}
```

**Comment by mmarkelov** [comment]
@mrgreenward можно так:
```
load: ["Layer", "projection.sphericalMercator"]
```
Чтобы использовать только необходимые пакеты

**Comment by mrgreenward** [comment]
Спасибо!

**Comment by innerdev** [comment]
@mrgreenward подскажите, как это вообще может работать? В вашем компоненте же не определен ymaps или я не понимаю? Мне нужен доступ к нему тоже.

```
const { ymaps } = this.state;
```

**Comment by mrgreenward** [comment]
> @mrgreenward подскажите, как это вообще может работать? В вашем компоненте же не определен ymaps или я не понимаю? Мне нужен доступ к нему тоже.
> 
> ```
> const { ymaps } = this.state;
> ```

@innerdev.  Приветствую. Сначала в компоненте, где подключаете  карту  задайте this.state = {ymaps = null}.
Затем добавляем функцию-метод, которая через параметр обновить cтейт "ymaps":
`setYmaps = ymaps => {
        this.setState({ ymaps });
    }`
Далее пробрасываем через "onLoad" данные в наш стейт с помощью указанной выше функции :
`  <Map
                    instanceRef={ref => (this.map = ref)}
                    onLoad={ymaps => {this.setYmaps(ymaps)}}
                    state={{
                        center: this.state.mapFocus,
                        zoom: this.state.mapZoom,
                        controls: ['zoomControl']
                    }}>`
После этого можно работать с "ymaps по документации от API Яндекс карт.

**Comment by innerdev** [comment]
@mrgreenward Большое спасибо! <3

**Comment by BakytzhanAkzhol** [comment]
Привет всем. Я хочу добавить Circle при наведение маркера, но не получается. Моя цель -  это показать радиус его возможного местаположение на маркере. Но у меня не удаеться получить новый обьект Circle и добавить. 
Ошибка: ``TypeError: _this.map.Circle is not a function``
Мой код; 
```
objectManager = React.createRef();
map = React.createRef();

onHoverMarker(e){
       //Добавляю круг
       var objectId = e.get('objectId');
      //Падает: TypeError: _this.map.Circle is not a function
       var circle = this.map.Circle([[45, 75], 500], {}, {
       });
       this.map.current.geoObjects.add(circle);
     
}

onLeaveMarker(){
    //Удаляю круг
}
render(){
   return <YMaps>
      <Map
         state={this.state.mapState}
         instanceRef={this.map}
         >
            <ObjectManager 
               modules={["objectManager.addon.clustersHint", "objectManager.addon.clustersBalloon",          "objectManager.addon.objectsBalloon", "objectManager.addon.objectsHint"]}
               instanceRef={(obj) => this.objectManager = obj}
               options={{
                  clusterize: false,
                  gridSize: 10,
               }}
               objects={{
                  preset: 'islands#greenDotIcon',
               }}
               clusters={{
                  preset: 'islands#greenClusterIcons',
               }}
               onMouseEnter={this.onHoverMarker}
               onMouseLeave={this.onLeaveMarker}
               features={this.state.features}
               />
      </Map>
   </Ymaps>
```
Я хочу добавить Circle из примера в документаций Яндекс, но не получается.
```
// Создаем геодезический круг радиусом 1000 километров.
var circle = new ymaps.Circle([[50, 75], 1000000], {}, {
    geodesic: true
});
// Добавляем круг на карту.
myMap.geoObjects.add(circle);
```

**Comment by mmarkelov** [comment]
@BakytzhanAkzhol во первых нужно добавить Круг в модули:
```modules={['Circle']}```

А во вторых **Circle** принадлежит непосредственно объекту **ymaps** но не самой карте

**Comment by BakytzhanAkzhol** [comment]
Спасибо за быстрый ответь. Ваууу. У меня таким способом заработало без добавление ``modules={['Circle']}``. 

```
 circle = {};
 onObjectEvent = (e) => {
        let objectId = e.get('objectId');
        this.circle = new this.ymaps.current.Circle([[45,75], 500], {}, {});
        this.map.current.geoObjects.add(this.circle);
 };
```


Другой последний вопрос. Как удалить Circle из geoObjects?
**Ошибка**: `` _this.map.current.geoObjects.forEach is not a function``

```
    onObjectLeave = (e) => {
        console.log('geoObjects', this.map.current.geoObjects);

        this.map.current.geoObjects.forEach((object, index) => {
            if (object == this.circle) {
                this.map.current.geoObjects.remove(object);
                this.circle = {};
            }
        })
    };
```

**Comment by Defite** [comment]
> > @mrgreenward подскажите, как это вообще может работать? В вашем компоненте же не определен ymaps или я не понимаю? Мне нужен доступ к нему тоже.
> > ```
> > const { ymaps } = this.state;
> > ```
> 
> @innerdev. Приветствую. Сначала в компоненте, где подключаете карту задайте this.state = {ymaps = null}.
> Затем добавляем функцию-метод, которая через параметр обновить cтейт "ymaps":
> `setYmaps = ymaps => { this.setState({ ymaps }); }`
> Далее пробрасываем через "onLoad" данные в наш стейт с помощью указанной выше функции :
> ` <Map instanceRef={ref => (this.map = ref)} onLoad={ymaps => {this.setYmaps(ymaps)}} state={{ center: this.state.mapFocus, zoom: this.state.mapZoom, controls: ['zoomControl'] }}>`
> После этого можно работать с "ymaps по документации от API Яндекс карт.

Это не работает и state всегда пустой.

**Comment by Defite** [comment]
> > @mrgreenward подскажите, как это вообще может работать? В вашем компоненте же не определен ymaps или я не понимаю? Мне нужен доступ к нему тоже.
> > ```
> > const { ymaps } = this.state;
> > ```
> 
> @innerdev. Приветствую. Сначала в компоненте, где подключаете карту задайте this.state = {ymaps = null}.
> Затем добавляем функцию-метод, которая через параметр обновить cтейт "ymaps":
> `setYmaps = ymaps => { this.setState({ ymaps }); }`
> Далее пробрасываем через "onLoad" данные в наш стейт с помощью указанной выше функции :
> ` <Map instanceRef={ref => (this.map = ref)} onLoad={ymaps => {this.setYmaps(ymaps)}} state={{ center: this.state.mapFocus, zoom: this.state.mapZoom, controls: ['zoomControl'] }}>`
> После этого можно работать с "ymaps по документации от API Яндекс карт.

Полная чушь написана. `state` будет `null` и дальше отрисовка компонента упадет с ошибкой.

**Comment by mmarkelov** [comment]
> > > @mrgreenward подскажите, как это вообще может работать? В вашем компоненте же не определен ymaps или я не понимаю? Мне нужен доступ к нему тоже.
> > > ```
> > > const { ymaps } = this.state;
> > > ```
> > 
> > 
> > @innerdev. Приветствую. Сначала в компоненте, где подключаете карту задайте this.state = {ymaps = null}.
> > Затем добавляем функцию-метод, которая через параметр обновить cтейт "ymaps":
> > `setYmaps = ymaps => { this.setState({ ymaps }); }`
> > Далее пробрасываем через "onLoad" данные в наш стейт с помощью указанной выше функции :
> > ` <Map instanceRef={ref => (this.map = ref)} onLoad={ymaps => {this.setYmaps(ymaps)}} state={{ center: this.state.mapFocus, zoom: this.state.mapZoom, controls: ['zoomControl'] }}>`
> > После этого можно работать с "ymaps по документации от API Яндекс карт.
> 
> Полная чушь написана. `state` будет `null` и дальше отрисовка компонента упадет с ошибкой.

Стэйт то почему будет **null**?  **ymaps** еще может быть да.  Естественно нужно будет делать проверку на существование **ymaps**, а еще лучше использовать **ref** вместо **state**

**Comment by gribnoysup** [comment]
@Defite пожалуйста, поддерживайте уважительный тон беседы
