### ISSUE TITLE
How to use GeoObjectCollection or util.bounds modules without ymaps.modules.require?

### ISSUE THREAD

**Issue by methodnumber13** [gribnoysup/react-yandex-maps#143]
Hi! I am trying to use 'GeoObjectCollection'  and 'util.bounds' modules like this
`ymaps.modules.require(['Placemark', 'GeoObjectCollection', 'util.bounds'], (Placemark, GeoObjectCollection, bounds) => { some code}` and all is ok, but I want know how it may make with your wrap over yandex maps API, if it possible. Can you provide any methods/samples?

**Comment by mmarkelov** [comment]
@methodnumber13 You can use **Placemark**, **util.bounds** like so:
[![Edit 0q2yk0pn3w](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0q2yk0pn3w)
