### ISSUE TITLE
Можно ли отключить кнопку Как добраться на карте? 

### ISSUE THREAD

**Issue by lashevskiy** [gribnoysup/react-yandex-maps#144]
Можно ли на карте убрать кнопку "Как добраться" ?  
<img width="282" alt="Снимок экрана 2019-03-16 в 20 48 02" src="https://user-images.githubusercontent.com/6946420/54479343-e177da80-482c-11e9-82b0-5daf9ed58d4d.png">

**Comment by mmarkelov** [comment]
@lashevskiy есть опция **suppressMapOpenBlock**:
```javascript
<Map ... options={{suppressMapOpenBlock: true}} />
```
