### ISSUE TITLE
Можно ли закрывать balloon при нажатии на карту 

### ISSUE THREAD

**Issue by lashevskiy** [gribnoysup/react-yandex-maps#145]
Добрый день! 

Использую карту с кластером. Внутри кластера массив Placemark с balloonContentBody. 
Соответственно, при нажатии на Placemark открывается balloon с его содержимым. Можно ли при нажатии на карту автоматически закрывать открытый balloon? Не удается разобраться с данным кейсом

**Comment by mmarkelov** [comment]
@lashevskiy Можно - слушаешь клик по карте и закрываешь балун:

[![Edit react-yandex-maps issue #145](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yj1qj8r02x?fontsize=14)
