### ISSUE TITLE
Не работает GeolocationControlExample ?

### ISSUE THREAD

**Issue by golubvladimir** [gribnoysup/react-yandex-maps#146]
Беру стандартный пример из документации.
Все равно кнопка со стрелочкой не выводиться.

"react-yandex-maps": "3.0.2",

**Comment by mmarkelov** [comment]
@golubvladimir можно код
У меня все [работает](https://react-yandex-maps.now.sh/controls/geolocation-control)

**Comment by golubvladimir** [comment]
можно закрыть проблема была у меня
