### ISSUE TITLE
Как получить zoom карты, если карта вызывается с помощью bounds ?

### ISSUE THREAD

**Issue by golubvladimir** [gribnoysup/react-yandex-maps#149]
Делаю так:

                <YMaps
                    onApiAvaliable={(ymaps) => this.handleApiAvaliable(ymaps)}
                >

Потом получаю этот объект:

    handleApiAvaliable(ymaps) {
        console.log(ymaps);
    }

Но не могу найти, где именно он находиться ?

**Comment by mmarkelov** [comment]
@golubvladimir В третьей версии нет метода [**onApiAvaliable**](https://react-yandex-maps.now.sh/migration-guide#onapiavaliable-is-removed-from-the-library)

**Comment by golubvladimir** [comment]
@mmarkelov использую 2.2.0

**Comment by golubvladimir** [comment]
@mmarkelov вроде есть ymaps.Map.getZoom, но оно не работает.

**Comment by mmarkelov** [comment]
@golubvladimir 
[![Edit jnr4182wxy](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnr4182wxy?fontsize=14)

**Comment by golubvladimir** [comment]
@mmarkelov Спасибо, проблема решена.
