### ISSUE TITLE
Свой шаблон для балунов ?

### ISSUE THREAD

**Issue by golubvladimir** [gribnoysup/react-yandex-maps#150]
Поискав нашел только это https://github.com/gribnoysup/react-yandex-maps/issues/27

Больше никаких способов решения данной проблемы нет ?

**Comment by mmarkelov** [comment]
@golubvladimir Лучше посмотреть здесь https://github.com/gribnoysup/react-yandex-maps/issues/130
Если Вам нужна просто разметка внутри балуна без логики, то стоит использовать [**ymaps.templateLayoutFactory**](https://tech.yandex.ru/maps/jsbox/2.1/balloon_html)

**Comment by EgorKluch** [comment]
У меня хорошо сработал вариант `ReactDOM.portal`. Еще тестирую, но вроде все прям отлично работает, на `balloonopen` отрисовываю элемент.

**Comment by 2gnc** [comment]
> У меня хорошо сработал вариант `ReactDOM.portal`. Еще тестирую, но вроде все прям отлично работает, на `balloonopen` отрисовываю элемент.
> 
> Кто сталкивался со сложностями?

Тоже занимаюсь аналогичной задачей. А можешь показать пример, где можно событие открытия балуна описать?
