### ISSUE TITLE
How to open specific ballon by click on a button?

### ISSUE THREAD

**Issue by kotchuprik** [gribnoysup/react-yandex-maps#156]
I have a list with an address list and when a user clicks on an address balloon must open. How I can implement this? Plus I'm using the cluster feature.

A rough example:

[![react-yandex-maps issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l26xz4x98m?fontsize=14)

I tried to do an array with refs and then search a ref and open but it's ugly and works only without the cluster feature.

I think much relevant doc article is https://tech.yandex.ru/maps/jsbox/2.1/object_manager_balloon, I didn't try ObjectManager and I will go to try it in a few mins :)

Thanks!

**Comment by mmarkelov** [comment]
@kotchuprik i think you will understand idea:
[![Edit react-yandex-maps issue #165](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r7qw0yn1lo?fontsize=14)

**Comment by kotchuprik** [comment]
thanks! that looks good for me, going to check for my case.

**Comment by kotchuprik** [comment]
well, I have another question :D how I can zoom to cluster automatically? I do not need two column balloon view I need just open balloon X for button X.

**Comment by kotchuprik** [comment]
I did it! I just must to add `instanceRef={ref => this.map = ref}` to my Map and then `this.map.setCenter` :)
