### ISSUE TITLE
Is it possible to use multiRouter?

### ISSUE THREAD

**Issue by sou1est** [gribnoysup/react-yandex-maps#157]
As I understood there is route module support, but I could not manage to enable multiRouter?
Would be glad if someone can point to it or show workaround.
Thanks in advance.

**Comment by mmarkelov** [comment]
@sou1est you can check this sandbox:
[![Edit react-yandex-maps3 multiRouter](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p3vnvk2q7x?fontsize=14)
