### ISSUE TITLE
react-yandex-maps v3 построение маршрута

### ISSUE THREAD

**Issue by AVeselov95** [gribnoysup/react-yandex-maps#158]
Пример из #68 не работает 
использую "react-yandex-maps": "^3.0.2"

**Comment by AVeselov95** [comment]
про то что onApiAvaliable удален и нужно использовать onLoad знаю

**Comment by gribnoysup** [comment]
Демо из #68 с изменениями описаными в ["Migration Guide"](https://react-yandex-maps.now.sh/migration-guide): https://codesandbox.io/s/mmv6034848?fontsize=14

Пожалуйста, читайте ["Migration Guide"](https://react-yandex-maps.now.sh/migration-guide), там описаны все breaking changes из v3 и как изменить код из v2 что бы он работал в v3
