### ISSUE TITLE
Как получить изменения объекта Polygon в режиме редактирования

### ISSUE THREAD

**Issue by marenkoviktor1992** [gribnoysup/react-yandex-maps#162]
Добрый день, подскажите пожалуйста есть возможность получить у <Polygon /> изменение координат точек? Возможно есть какой-нибудь пропс например onChange

**Comment by mmarkelov** [comment]
@marenkoviktor1992 примерно так:
[![Edit react-yandex-maps editable Polygon](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-swirles-6w23s?fontsize=14)
Есть достаточное количество событий, на которые вы можете подписаться - (дока)[https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/geometryEditor.Polygon-docpage/]
