### ISSUE TITLE
Geolocation не работает

### ISSUE THREAD

**Issue by tsepen** [gribnoysup/react-yandex-maps#165]
Как получить город пользователя? Данный [пример](https://codesandbox.io/s/suspicious-river-z6hxm) не работает. Спасибо
```javascript
import React from "react";
import ReactDOM from "react-dom";
import { YMaps } from "react-yandex-maps";

import "./styles.css";
const getGeoLocation = ymaps => {
  return ymaps.geolocation
    .get({ provider: "yandex", mapStateAutoApply: true })
    .then(result =>
      ymaps.geocode(result.geoObjects.position).then(res => {
        let firstGeoObject = res.geoObjects.get(0);
        console.log(
          firstGeoObject.getLocalities().length
            ? firstGeoObject.getLocalities()
            : firstGeoObject.getAdministrativeAreas()
        );
      })
    );
};

const handleApiAvaliable = ymaps => {
  const geolocation = getGeoLocation(ymaps);

  console.log(geolocation)
};

function App() {
  return (
    <div className="App">
      <YMaps onApiAvaliable={ymaps => handleApiAvaliable(ymaps)} />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by mmarkelov** [comment]
@tsepen Данный пример не совместим с последней версией пакета. Он написан под предыдущую версию. Для текущей версии:
[![Edit focused-pond-z51bn](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-pond-z51bn?fontsize=14)
Перед открытием issue, настоятельно рекомендую читать документацию, в особенности [это](https://react-yandex-maps.now.sh/migration-guide)
Спасибо!

**Comment by RokeAlvo** [comment]
подниму ветку, пример в песочнице не работает. не подскажите, куда смотреть?
`import React from 'react'
import './Map.css'
import { Map, YMaps } from 'react-yandex-maps'


export default function(props) {
  const onLoadMap = (inst) => {
    var location = window.ymaps.geolocation.get(
      { mapStateAutoApply: true },
    )
    console.log('ymaps  ', window.ymaps)
// Асинхронная обработка ответа.
    location.then(
      function(result) {
        // Добавление местоположения на карту.
        console.log('location ', result)
        result.geoObjects.options.set('preset', 'islands#redCircleIcon');
        result.geoObjects.get(0).properties.set({
          balloonContentBody: 'Мое местоположение'
        });
        inst.geoObjects.add(result.geoObjects);      },
      function(err) {
        console.log('Ошибка: ' + err)
      },
    )
  }
  const [zoom, setZoom] = React.useState(15)
  // const setZoom = zoom=>zoom
  const [center, setCenter] = React.useState(
    [66.08, 76.6931577],
  )
  const mapState = React.useMemo(() => ({ center, zoom }),
    [center, zoom,
    ])
  return (
    <YMaps query={{
      apikey: 'beed9c5f-1272-42be-8cc0-0d9741975e6b',
    }}>
      <div>
        <Map onLoad={(inst) => onLoadMap(inst)}
             className='map-container'
             state={mapState}
        >
        </Map>
      </div>
    </YMaps>
  )
}

`

**Comment by RokeAlvo** [comment]
Подниму ветку, пример в песочнице не работает, но это, я думаю связано с безопасностью соединения...
У меня вот такой код не работает:
`import React from 'react'
import './Map.css'
import { Map, YMaps } from 'react-yandex-maps'


export default function(props) {
  const onLoadMap = (inst) => {
    var location = window.ymaps.geolocation.get(
      { mapStateAutoApply: true },
    )
    console.log('ymaps  ', window.ymaps)
// Асинхронная обработка ответа.
    location.then(
      function(result) {
        // Добавление местоположения на карту.
        console.log('location ', result)
        result.geoObjects.options.set('preset', 'islands#redCircleIcon');
        result.geoObjects.get(0).properties.set({
          balloonContentBody: 'Мое местоположение'
        });
        inst.geoObjects.add(result.geoObjects);      },
      function(err) {
        console.log('Ошибка: ' + err)
      },
    )
  }
  const [zoom, setZoom] = React.useState(15)
  // const setZoom = zoom=>zoom
  const [center, setCenter] = React.useState(
    [66.08, 76.6931577],
  )
  const mapState = React.useMemo(() => ({ center, zoom }),
    [center, zoom,
    ])
  return (
    <YMaps query={{
      apikey: 'my_api',
    }}>
      <div>
        <Map onLoad={(inst) => onLoadMap(inst)}
             className='map-container'
             state={mapState}
        >
        </Map>
      </div>
    </YMaps>
  )
}

`

**Comment by mmarkelov** [comment]
@RokeAlvo я не вижу у вас подключения модулей в коде. Думаю, что проблема в этом:
```javascript
        <Map 
             modules={["geolocation", "geocode"]}  
             onLoad={(inst) => onLoadMap(inst)}
             className='map-container'
             state={mapState}
        >
```

**Comment by Shakxzod-Namazbaev** [comment]
```
const getGeoLocation = ymaps => {
    return ymaps.geolocation
      .get({ provider: "yandex", mapStateAutoApply: true })
      .then(result =>
        ymaps.geocode(result.geoObjects.position).then(res => {
          res.geoObjects.get(0).geometry.getCoordinates();
        })
      );
  };
```
