### ISSUE TITLE
Карта в попапе каждый раз при открытии заново грузит yandex maps api

### ISSUE THREAD

**Issue by Volosojui** [gribnoysup/react-yandex-maps#167]
Есть ли какие-то способы избежать повторной загрузки апи карт? Может кто-то уже решал подобную задачу. В поиске ничего похожего не нашёл.
Заранее спасибо!

**Comment by mmarkelov** [comment]
@Volosojui хороший вопрос, есть параметр **ns**, как я понимаю, он решает эту задачу. Возможно есть подводные камни, @gribnoysup поправь, если я ошибаюсь. Будет выглядеть примерно так:
```javascript
<YMaps query={{ ns: 'YMaps' }}>
  <Map .../>
</YMaps>
```

**Comment by Volosojui** [comment]
@mmarkelov Спасибо! Помогло)

**Comment by gribnoysup** [comment]
@mmarkelov всё так!

@Volosojui я так понимаю, что код у тебя был _примерно_ такой:

```jsx
render() {
  return this.state.open && <YMaps><Map /><YMaps>
}
```

Правильно?

В таком случае либо `query.ns`, как написал @mmarkelov (в текущей версии [кода доков](https://github.com/gribnoysup/react-yandex-maps/blob/31dc577210d43ce7add64f4941cabc0a505f13f3/docs/components/LiveEditor.js#L20) этот `prop` используется что бы можно было в примерах рендерить YMaps компонент в каждой песочнице, но не грузить карты каждый раз), либо поднять провайдер выше в дереве:

```jsx
render() {
  return <YMaps>{this.state.open && <Map />}<YMaps>
}
```

Карты не начнут грузиться пока хотя бы один компонент из библиотеки (исключая провайдер) не будет отрендерен реактом

Об этом [есть строчка в документации](https://react-yandex-maps.now.sh/#adding-maps-to-your-application), но думаю надо будет выделить этот момент сильнее в новой версии.

**Comment by Volosojui** [comment]
@mmarkelov Спасибо за подробное объяснение!

По поводу моего случая - да, был первый вариант (тут всё упиралось в модкалку, которая рендерилась во внешнем контейнере):
`
render() {
  return (
    <Modal isOpen={this.state.isModalOpen}>
      <YMaps><Map /><YMaps>
    </Modal>
  );
}
`
