### ISSUE TITLE
Не подключаются controls

### ISSUE THREAD

**Issue by vinera** [gribnoysup/react-yandex-maps#168]
Добрый день! Не отображаются элементы управления. Ошибок не выдает.

```
const placeMark = {
      geometry: [56.848217, 53.236675],
      properties: {
          hintContent: hotel,
          balloonContent: hotel
      },      
      modules: ['geoObject.addon.balloon', 'geoObject.addon.hint']
    }
```

```
 <YMaps >
          <Map state={mapState}>
            <Placemark {...placeMark}/>
            <ZoomControl />
          </Map>
</YMaps>
```

react: 15.3.2
react-yandex-maps: 3.0.2

**Comment by mmarkelov** [comment]
@vinera не совсем понятно о каких элементах идет речь - в вашем случае будет только то, что вы добавили - **ZoomControl**. Остальные элементы контроля стоит добавлять аналогично - весь список в [доке](https://react-yandex-maps.now.sh/), раздел **Controls**

**Comment by vinera** [comment]
Я его привела как пример, в данном случае не отображается ZoomControl

**Comment by mmarkelov** [comment]
@vinera В вашем примере ошибки не вижу, хотя что-то мне подсказывает, что это связанно с вашей версией реакта. У вас есть возможность обновиться?

**Comment by mmarkelov** [comment]
@vinera точно все работает с версией от 16.3, @gribnoysup предлагаю дропнуть все что раньше из **package.json**

**Comment by vinera** [comment]
Да, я тоже думаю связано с версией реакта. Обновиться, к сожалению, не могу. А какая версия карт пойдет с 15 реактом, и где можно посмотреть док-цию к ней?

**Comment by mmarkelov** [comment]
@vinera с версией 2.2.0 должно работать
[дока](https://github.com/gribnoysup/react-yandex-maps/tree/v2.2.0)
и пример:
[![Edit react-yandex-maps issue #74](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/llq5z3v76m?fontsize=14)

**Comment by vinera** [comment]
версия 2.2.0 выдает такую ошибку:

client:75 ./~/react-yandex-maps/dist/react-yandex-maps.umd.production.min.js
Module build failed: Error: ENOENT: no such file or directory, open '/app/node_modules/react-yandex-maps/dist/react-yandex-maps.umd.production.min.js'
    at Error (native)

При переключении обратно на 3.0.2 она пропадает.  В codesanbox всё работает нормально. Подключаю пакеты через npm. В чем может быть проблема?

**Comment by mmarkelov** [comment]
@vinera  попробуйте удалить **node_modules** и переустановить зависимости

**Comment by vinera** [comment]
Всё получилось, большое спасибо за помощь!
