### ISSUE TITLE
карта не сразу отображается

### ISSUE THREAD

**Issue by SerzhanHelena** [gribnoysup/react-yandex-maps#170]
Почему-то карта не сразу отображается при загрузке компонента 
```
    const mapState = {
      center: [54.1, 28.36],
      zoom: 11
    };
         <div style={{width: '100%', height: '100%'}} className={style.map}>
            <YMaps>
              <Map instanceRef={ref => { ref && ref.behaviors.disable('scrollZoom'); }}
                 state={mapState}>
                <ZoomControl
                  options={{
                    zoomDuration: 1000
                  }}
                />
                <Placemark
                  {...placeMark}
                  modules={["geoObject.addon.balloon", "geoObject.addon.hint"]}
                />
              </Map>
            </YMaps>
```

**Comment by mmarkelov** [comment]
@SerzhanHelena не совсем понятно, что значит не сразу отображается. Было бы неплохо пример в песочнице и то, что вы ожидаете получить

**Comment by SerzhanHelena** [comment]
смотрите, у меня есть страничка "Контакты", которая содержит карту и контактную информацию. При переходе на эту страницу контактная информация сразу загружается (т.е блок <div> c информацией), а карта отображается спустя несколько секунд. Я хотела бы узнать,  можно ли как-то ускорить отрисовку карты?

**Comment by mmarkelov** [comment]
@SerzhanHelena я думаю речь идет о стандартном поведении [карты](https://tech.yandex.ru/maps/jsbox/2.1/request_map) - вы можете показывать плейсхолдер во время загрузки

**Comment by SerzhanHelena** [comment]
@mmarkelov , 6-7 секунд рендерится карта, как-то долго

**Comment by mmarkelov** [comment]
@SerzhanHelena  6 - 7 секунд согласен, что много. Но я не вижу как с этим может быть связана библиотека, проверил в [примерах](https://codesandbox.io/s/p3vnvk2q7x), все нормально

**Comment by alexkuz** [comment]
@mmarkelov возможно дело в этом:
https://github.com/gribnoysup/react-yandex-maps/blob/master/src/YMaps.js#L27
из-за хеша каждый раз формируется новый урл и ответ браузера не кешируется.
Как быстрый фикс, я бы предложил опционально указывать хеш в пропсах YMaps
