### ISSUE TITLE
На большом количестве меток с кластеризацией карта блокирует основной поток

### ISSUE THREAD

**Issue by Volosojui** [gribnoysup/react-yandex-maps#172]
https://codesandbox.io/embed/vigorous-khorana-zxwjb 
Показал для 500 точек, хотя у нас на проекте ещё больше.

Насколько я помню, апи яндекс карт при кластеризации не блокирует основной поток (браузер не подвисает на несколько секунд).

**Comment by gribnoysup** [comment]
`react-yandex-maps` использует апи яндекс карт, так что разницы никакой не будет если использовать `Clusterer` + `Placemark` вручную. Если вы рендерите большое число маркеров, то лучше использовать [`ObjectManager`](https://react-yandex-maps.now.sh/geo-objects/object-manager)

**Comment by sntptrck** [comment]
Тоже сталкивался с такой проблемой, из-за этого остался на версии 2.3. Приму к сведению совет с ObjectManager, спасибо

**Comment by Volosojui** [comment]
> `react-yandex-maps` использует апи яндекс карт, так что разницы никакой не будет если использовать `Clusterer` + `Placemark`. Если вы рендерите большое число маркеров, то лучше использовать [`ObjectManager`](https://react-yandex-maps.now.sh/geo-objects/object-manager)

Ок, спасибо. Отпишусь, когда перейдём на `ObjectManager`

По поводу апи яндекс карт понял, я подумал возможно быть прослойка `Clustered` вызывает такие глюки.

**Comment by Volosojui** [comment]
@gribnoysup Переделали на ObjectManager, всё летает. Спасибо! Закрываю
