### ISSUE TITLE
Add react-yandex-maps to plugins section

### ISSUE THREAD

**Issue by mmarkelov** [gribnoysup/react-yandex-maps#173]
Maybe we should ask **Yandex** to add library to [package list](https://tech.yandex.ru/maps/jsapi/#plugins)? It should be helpful for people, who use official docs

**Comment by gribnoysup** [comment]
I had no idea that this section exists because it's not there in the english version of the docs :D Well, yeah, I don't mind that, I'm not sure what is the process of getting there though

**Comment by mmarkelov** [comment]
@gribnoysup yeah! I suppose I can write to **Yandex** support about package. I just want to know that it would be ok)

**Comment by gribnoysup** [comment]
Totes! Go for it! 🎉

**Comment by mmarkelov** [comment]
@gribnoysup I send all needed information to Yandex support. They will give their decision soon, so I close issue, when they answered

**Comment by mmarkelov** [comment]
**Yandex** just added library to their [package list](https://tech.yandex.ru/maps/jsapi/#plugins). I just want to believe that it will be helpful for Russian community.

**Comment by gribnoysup** [comment]
I guess I'll start thinking about how to localize the docs 😄
