### ISSUE TITLE
Is it possible to set cluster "preset" according to data to the cluster of object manager?

### ISSUE THREAD

**Issue by kuanysh-nabiyev** [gribnoysup/react-yandex-maps#176]
If sum of quantity of property1 is more than sum of quantity if property2 in one cluster then I need set cluster "preset" to red color. Otherwise,  the cluster "preset" shoud be blue color

**Comment by mmarkelov** [comment]
@kuanysh-nabiyev i don't understand what do you exactly want

**Comment by kuanysh-nabiyev** [comment]
@mmarkelov sorry
I want to set different colors according to cluster data like in the following image.
![image](https://user-images.githubusercontent.com/5706213/60000649-738e4b00-9686-11e9-9c2b-90cecec06235.png)

Cluster color is always black, but I want to set them blue or red
![image](https://user-images.githubusercontent.com/5706213/60000963-2f4f7a80-9687-11e9-8977-25f7a0003613.png)

**Comment by mmarkelov** [comment]
Like so:
[![Edit staging-river-cbzq4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/staging-river-cbzq4?fontsize=14)
Check it [here](https://romua1d.ru/klasterizatsiya-tochek-na-yandex-kartah-iz-json/)

**Comment by kuanysh-nabiyev** [comment]
@mmarkelov yes, but I want to group them by information in objects of a cluster. 
Your example groups by quantity of objects in cluster

**Comment by kuanysh-nabiyev** [comment]
@mmarkelov http://adilsailau.kz
Your can choose Алматы city

**Comment by shmidtelson** [comment]
> @kuanysh-nabiyev Like so:
> [![Edit staging-river-cbzq4](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/staging-river-cbzq4?fontsize=14)
> Check it [here](https://romua1d.ru/klasterizatsiya-tochek-na-yandex-kartah-iz-json/)

404 error
