### ISSUE TITLE
Is it possible to realize yandex maps regions feature?

### ISSUE THREAD

**Issue by kuanysh-nabiyev** [gribnoysup/react-yandex-maps#177]
Example,
https://tech.yandex.ru/maps/jsbox/2.1/regions_colors

**Comment by mmarkelov** [comment]
@kuanysh-nabiyev you can implement all kind of examples with this library:
[![Edit react-yandex-maps regions](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wandering-snow-xzl1y?fontsize=14)

**Comment by kuanysh-nabiyev** [comment]
@mmarkelov thx
