### ISSUE TITLE
Перевод пиксельных координат в географические.

### ISSUE THREAD

**Issue by oddzye** [gribnoysup/react-yandex-maps#178]
По событию onDragEnd в обработчик приходит массив из координат в пикселях, можно ли каким-то образом преобразовать эти координаты к географическим? Можно ли сделать это через проекцию, если да, то как к ней обратиться?Такой пример есть 
в документации yandex maps. - `map.options.get('projection').toGlobalPixels(coords, map.getZoom())`

**Comment by gribnoysup** [comment]
Доступ к экземпляру `Map` можно получить с помощью свойства `instanceRef`, а дальше делать с ним что угодно. Так же коордитаны можно получить прямо из события `onDragEnd`:

[![Edit friendly-wood-5bc5d](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-wood-5bc5d?fontsize=14)

**Comment by oddzye** [comment]
@gribnoysup Спасибо огромное, не увидел этого в объекте сначала.
