### ISSUE TITLE
SearchControl расширенные возможности

### ISSUE THREAD

**Issue by denismart** [gribnoysup/react-yandex-maps#179]
Приветствую!
Во-первых огромный респект за такую замечательную либу.

Столкнулся с несколькими вопросами. 
1. Есть ли какой-то евент у SearchControl, отвечающий за отлавливание события нажатия на крестик (который удаляет метку и очищает саму строку поиска).
2. Есть ли возможность очистить SearchControl и удалить поставленную им метку принудительно (программно)?
3. Повтор этого тикета https://github.com/gribnoysup/react-yandex-maps/issues/18
К сожалению, код, который вы приводите в примере того тикета не открывается. Но вопрос тот же, как у SearchControl в onChange отлавливать выбранную координату.

Спасибо!
С уважением,  Денис.

**Comment by mmarkelov** [comment]
@denismart 
1. Есть ивент clear. [Яндекс Дока](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/control.SearchControl-docpage/)
```javascript
...
<SearchControl onClear={() => console.log("clear")} />
...
```
По остальным вопросам песочница:
[![Edit agitated-glitter-6tsev](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-glitter-6tsev?fontsize=14)

p.s. Песочницы примеров также периодически становятся недоступными - советую их форкать

**Comment by gribnoysup** [comment]
@mmarkelov маленькая поправочка, с `instanceRef` лучше использовать `useRef` а не `useState`. При использовании `useState` React будет перерендеривать всё дерево на каждом апдейте свойств на компонентах, а в данном случае это не обязательно

[![Edit priceless-hoover-gmosy](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-hoover-gmosy?fontsize=14)
