### ISSUE TITLE
Получение данных из SearchControl

### ISSUE THREAD

**Issue by stfoo** [gribnoysup/react-yandex-maps#18]
Привет! Я пытаюсь сделать простейший виджет для получения координат по адресу и запутался.

У меня есть такая карта:
```jsx
<YMaps>
  <Map>
    <SearchControl onResultShow={this.onResultShow} />
  </Map>
</YMaps>
```
В `onResultShow` я получаю только событие, в котором есть только индекс выбранного адреса. Если и сами адреса, но они закопаны в приватных свойствах.

Из АПИ Яндекс.Карт я узнал, что для получения данных о выбранной точке нужно использовать метод `searchControl.getResult(index)`, но я не понимаю, как мне получить инстанс контрола. Я попробовал `ref`, но получаю `null`. 

Возможно, мне не хватает какого-то фундаментального понимая здесь. Направь меня, пожалуйста.

**Comment by gribnoysup** [comment]
Привет, получить доступ к самому контролу ты можешь с помощью [instanceRef](https://github.com/gribnoysup/react-yandex-maps#the-instanceref-callback-attribute)
