### ISSUE TITLE
Программное получение построенного через RouteEditor маршрута

### ISSUE THREAD

**Issue by DmitriyMetelskiy** [gribnoysup/react-yandex-maps#182]
Как программно построить маршрут в RouteEditor видел в других issue, огромное спасибо Вам за них. Здесь же меня интересует получение построенного через RouteEditor маршрута. В частности - получение wayPoints и viaPoints.
Опционально пояснить как то же самое проделать с activeRoute из RoutePanel.
Для конкретности получение маршрута с карты происходит по нажатию кнопки.
Этот маршрут невозможно получить через this.map.geoObjects, где же он хранится, и как его получить?

**Comment by mmarkelov** [comment]
@DmitriyMetelskiy привет!
Я обновил код в этой песочнице, но он возможно не будет работать из-за ограничений Яндекса :(
[![Edit react-yandex-maps3 multiRouter](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p3vnvk2q7x?fontsize=14)
Постараюсь объяснить:
```javascript
import React, { useState, useRef } from "react";
import ReactDOM from "react-dom";
import { YMaps, Map } from "react-yandex-maps";

import "./styles.css";

const mapState = { center: [55.750625, 37.626], zoom: 7 };

function App() {
  const [ymaps, setYmaps] = useState(null);
  // Завел для хранения маршрута переменную(аналогия переменной класса в стэйтлесс компоненте)
  const routes = useRef(null);

  // В данном случае строим маршрут сразу, но можно изменить и строить по клику на кнопку
  const getRoute = ref => {
    if (ymaps) {
      const multiRoute = new ymaps.multiRouter.MultiRoute(
        {
          // Описание опорных точек мультимаршрута.
          referencePoints: [[55.734876, 37.59308], "Москва, ул. Мясницкая"],
          // Параметры маршрутизации.
          params: {
            // Ограничение на максимальное количество маршрутов, возвращаемое маршрутизатором.
            results: 2
          }
        },
        {
          // Автоматически устанавливать границы карты так, чтобы маршрут был виден целиком.
          boundsAutoApply: true,
          // Внешний вид линии маршрута.
          routeActiveStrokeWidth: 6,
          routeActiveStrokeColor: "#fa6600"
        }
      );

     // Кладем полученный маршрут в переменную
      routes.current = multiRoute;
      ref.geoObjects.add(multiRoute);
    }
  };

  const getRoutes = () => {
    // Теперь в этой переменной можем получить инстанс маршрута
    console.log(routes.current.getWayPoints());
  };

  return (
    <div className="App">
      <YMaps>
        <Map
          modules={["multiRouter.MultiRoute"]}
          onLoad={ymaps => setYmaps(ymaps)}
          state={mapState}
          instanceRef={ref => ref && getRoute(ref)}
        />
        <button onClick={getRoutes}>Show route</button>
      </YMaps>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

В принципе можно достучаться до роута и без использования ref-переменной, а через **geoObjects**, но насколько я знаю его [доку](https://tech.yandex.ru/maps/archive/doc/jsapi/2.0/ref/reference/map.GeoObjects-docpage/) там можно только итерироваться по всем объектам, что кажется мне не особо хорошим решением.

Если будут вопросы - постараюсь ответить

**Comment by DmitriyMetelskiy** [comment]
@mmarkelov привет!

**Comment by DmitriyMetelskiy** [comment]
@mmarkelov привет!
Я пробовал получать через ref.geoObjects. Там 2 объекта. Один - программно нарисованный маршрут, второй, судя по всему, кнопка, генерируемая тегом <RouteEditor /> внутри <Map>, но я в этом не совсем уверен. Проблема в том, что я пытаюсь получить точки(way- и viaPoints) во первых, в читабельном виде(массив элементов - координат/строк), во вторых - маршрута, который построен не программно, а "с помощью тыков ЛКМ"(сначала на кнопку RouteEditor-а, потом - на 2 точки(может и больше, если захотелось добавить viaPoints после прорисовки маршрута, т.е. для его редактирования)

**Comment by mmarkelov** [comment]
@DmitriyMetelskiy обновил песочницу.
Этот [пример](https://tech.yandex.ru/maps/jsbox/2.1/router) не поможет? 
Просто вопросы по внутреннему АПИ карт немного выходят за рамки данной либы. У меня к сожалению, нет достаточно глубоких знаний по методам карт

**Comment by DmitriyMetelskiy** [comment]
@mmarkelov есть идея, как это можно попробовать провернуть, но нужно программно добавить на карту кнопку RouteEditor-а. Возможно, что для этого нужно подключить его в modules. Не подскажешь, как модуль называется?

**Comment by mmarkelov** [comment]
@DmitriyMetelskiy RouteEditor присутствует в пакете:
https://react-yandex-maps.now.sh/controls/route-editor

**Comment by DmitriyMetelskiy** [comment]
@mmarkelov Спасибо за помощь! Разобрался с документацией яндекса и всё получилось. Добавил в modules и control, после этого смог наконец достучаться до routeEditor через this.map.controls.get('routeEditor'). Далее можно читать документацию и смотреть методы. Получил координаты wayPoints-ов через:
this.map.controls.get('routeEditor').getRoute().getWayPoints().toArray().map((point)=>point.geometry.getCoordinates())

**Comment by DmitriyMetelskiy** [comment]
Закрываю issue. Классная библиотека)
