### ISSUE TITLE
Создание маркера по нажатию на кнопку. Разница между v2 и v4

### ISSUE THREAD

**Issue by legiorex** [gribnoysup/react-yandex-maps#188]
Здравствуйте, в одном из  Issue приведен пример кода, в котором по нажатию на кнопку строится маршрут. Вот этот пример.
https://codesandbox.io/s/p37m4lz4j7
Там используется react-yandex-maps v2 
Если перевести на версию 4, то это не будет работать. Я понял что надо использовать props onLoad - он возвращает aip карты. Но даже с учетом этого я не смог разобраться. 
Сейчас я взял код, который мне посоветовали ранее, переписал его на функциональный компонент с хуками.
https://codesandbox.io/s/little-voice-uiy3s
`<Map
          modules={["package.full"]}
          state={mapState}
          onLoad={ymaps => handleApiAvaliable(ymaps)}
          instanceRef={map}
        >`
onLoad - получаю api яндекс карты
instanceRef={map} - получаю экземпляр текущей карты
не знаю, правильно ли я понимаю. 
Мне надо при нажатии на кнопку - создавать маркер. Как это сделать я не знаю. Подскажите пожалуйста.

**Comment by legiorex** [comment]
Так, разобрался с этим. Теперь осталось добавляемые маркеры соединить в линию.

**Comment by legiorex** [comment]
Теперь и с соединением в линию разобрался.
https://codesandbox.io/s/little-voice-uiy3s
Конечно это только пример, но поведение получилось забавное. Жалко мало документации и примеров.

**Comment by oduvanka** [comment]
> https://codesandbox.io/s/little-voice-uiy3s
> Конечно это только пример, но поведение получилось забавное. Жалко мало документации и примеров.

По ссылке нет примера кода

**Comment by legiorex** [comment]
> @oduvanka 
> По ссылке нет примера кода
Поправил, https://codesandbox.io/s/stupefied-blackwell-u5nrp
Но минус тут в том, что если добавлять динамически какие либо гео объекты - происходит перерендер компонента. Из-за это при каждом рендере гео объект заново отрисовывается. 
Но я разобрался что да как. Документация и api у яндекс карт странноватая.
