### ISSUE TITLE
JS Map function does not work with curly braces

### ISSUE THREAD

**Issue by ranetkaSt** [gribnoysup/react-yandex-maps#19]
Please help me. I don't know why, but I have some problems with Js Array Map function in my code.

If i use smth like this:

>                         <YMaps ymapsParams...>
>                             <Map mapParams..>
>                                 {routes.map((route, i) => 
>                                     <Polygon polygonParams.../>
>                                 )}
>                             </Map>
>                         </YMaps>

Everything is okay.

But in case I use curly braces

>                         <YMaps ymapsParams...>
>                             <Map mapParams..>
>                                 {routes.map((route, i) => {
>                                     <Polygon polygonParams.../>
>                                 })}
>                             </Map>
>                         </YMaps>

There are no Polygon elements on my map and no errors provided in console.

Thank you in advance

**Comment by ranetkaSt** [comment]
I'm JS newby.
Sorry, it was my fault

**Comment by gribnoysup** [comment]
@ranetkaSt no worries! I was about to answer anyway 😉
