### ISSUE TITLE
Не перерисовываются иконки кластера

### ISSUE THREAD

**Issue by artpopov** [gribnoysup/react-yandex-maps#191]
Реализовано приложение в виде карты с геообъектами. Цвет меток завязан на определённую логику. При этом имеем следующую проблему: при обновлении компонента цвета кластеров (с иконками в виде круговой диаграммы) не изменяются, но метки при этом свои цвета меняют.

Чтобы понять суть проблемы, нажимайте на кнопку под картой в этом примере на sandbox: https://codesandbox.io/embed/peaceful-johnson-b792w

**Comment by gribnoysup** [comment]
Выглядит как баг Яндекс.Карт, как только я меняю зум, кластеры перерисовываются и меняют цвет

**Comment by gribnoysup** [comment]
Заменил `Clusterer` на `ObjectManager`, теперь кластеры меняют цвет а не кластеризованые `Points` не обновляются (обновляются но с хаком):

https://codesandbox.io/s/frosty-waterfall-d27tj

Я почти на 100% уверен что проблема не в библиотеке а где-то в Яндекс.Картах

**Comment by artpopov** [comment]
Спасибо, решение вполне устраивает
