### ISSUE TITLE
Способы задания и получения parent у Palcemark

### ISSUE THREAD

**Issue by vadimdanilov** [gribnoysup/react-yandex-maps#192]
В документации к [Placemark](https://tech.yandex.com/maps/jsapi/doc/2.1/ref/reference/Placemark-docpage/#Placemark__param-options) описана в методах возможность задания `parent`. Как аналогичную операцию можно произвести при помощи компонента `Placemark`?

**Comment by gribnoysup** [comment]
На любом компоненте можно получить доступ к инстансу яндекс карт и делать на нем любые операции, которые вам нужно:

```jsx
const ref = useRef(null);

useEffect(() => {
  console.log(ref);
}, [])

return <Placemark instanceRef={ref} />
```

Изменения `parent` скорее всего приведет к плохим последствиям, так как `parent` зависит от того где в React дереве находится компонент, так что делайте это на свой риск
