### ISSUE TITLE
Нечеткое изображение карты

### ISSUE THREAD

**Issue by AndreiGuk** [gribnoysup/react-yandex-maps#193]
У меня довольно простая реализация карт
`          

            <YMaps>
              <Map defaultState={{ center: [59.93059664553361, 30.32216204596321], zoom: 17 }}>
                <Placemark geometry={[59.93057241408524, 30.322129859455025]} />
              </Map>
            </YMaps>
`
Но сама карта недостаточно четкая.
Вот скрин с моего сайта
![Снимок экрана 2019-09-09 в 14 42 55](https://user-images.githubusercontent.com/48508646/64528224-9b4d9080-d310-11e9-95cd-8e1d9defd06e.png)

Вот пример из документации
![Снимок экрана 2019-09-09 в 14 42 49](https://user-images.githubusercontent.com/48508646/64528256-aa344300-d310-11e9-9ba7-80f1fec235e0.png)

В чем может быть проблема?

**Comment by mmarkelov** [comment]
@AndreiGuk смотрю через песочницу и такой проблемы не вижу. У меня нет предположений как библиотека может повлиять на изображение карты. Обертка над оригинальными картами достаточно тонкая - мы никак не меняем отображение. Возможно у Вас в стилях присутствует фильтр?

**Comment by AndreiGuk** [comment]
@mmarkelov я попробовал то же самое со свеженьким create-react-app, получил то же самое.

НО! размытая карта у меня только в хроме, остальные браузеры нормально отобразили. Более того, на боевом сервере все хорошо отобразилось и в хроме.

Вероятно, проблема не в этом пакете, так что я закрываю эту ветку.
