### ISSUE TITLE
Отключение ненужных модулей карты (поиск, пробки и прочие)

### ISSUE THREAD

**Issue by flour** [gribnoysup/react-yandex-maps#195]
Добрый день!
Вот для этого примера есть ли способ отключения ненужных модулей карты, таких как поиск, пробки и прочее? https://codesandbox.io/s/frosty-waterfall-d27tj

Я так понимаю нужно указать просто список загружаемых модулей для свойства modules, но какие это модули... вообще не понятно)

Спасибо!

**Comment by mmarkelov** [comment]
@flour способа отключения ненужных модулей нет - есть список нужных.
Для вашего примера это:
 `modules={["layout.PieChart", "objectManager.addon.clustersBalloon"]}`

По модульную систему лучше смотреть [здесь](https://tech.yandex.ru/maps/jsapi/doc/2.1/dg/concepts/modules-docpage/)

**Comment by flour** [comment]
Спасибо за подсказку!!
Буду копать1

**Comment by drmax24** [comment]
Это правда?

https://ru.stackoverflow.com/questions/1183849/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B0%D0%B7%D0%BD%D1%8B%D1%85-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2-api-%D0%BD%D0%B5-%D0%B2%D0%BB%D0%B8%D1%8F%D0%B5%D1%82-%D0%BD%D0%B0-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80-%D0%BF%D0%BE%D0%B4%D0%B3%D1%80%D1%83%D0%B6%D0%B0%D0%B5%D0%BC%D1%8B%D1%85-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2-js

Теперь ~687.3 KiB нужно качать всегда?
