### ISSUE TITLE
Как обратиться к setBounds

### ISSUE THREAD

**Issue by SinrVolcano** [gribnoysup/react-yandex-maps#200]
У яндекс карт есть метод который позиционирует карту, чтобы было видно две точки.
Если я не ошибаюсь то это он - [setBounds ](https://tech.yandex.ru/maps/archive/doc/jsapi/2.0/ref/reference/Map-docpage/#method_detail__setBounds)
Я не могу обратиться к нему через полученный класс в onLoad.
Через модули я например спокойно подгрузил 'geolocation', а как сделать это с setBounds не ясно.

**Comment by mmarkelov** [comment]
@SinrVolcano посмотрите #126 а также [доку](https://react-yandex-maps.now.sh/faq#how-to-get-object-instance)
