### ISSUE TITLE
Обязательный KEY ?

### ISSUE THREAD

**Issue by tsepen** [gribnoysup/react-yandex-maps#202]
Пытаюсь получить геопозицию 
`ymaps.geolocation
      .get({ provider: 'browser', mapStateAutoApply: true })`

Получаю ошибку про обязательный key, я получил key в личном кабинете, но как его передать?
` <YMaps>
                <Map
                  state={{ center: [0, 0], zoom: 9 }}
                  modules={['geolocation', 'geocode']}
                  onLoad={(ymaps) => getGeoLocation(ymaps)}
                />
   </YMaps>`

**Comment by mmarkelov** [comment]
@tsepen попробуйте так:
`<YMaps query={{ apikey: 'ваш ключ' }}>`

**Comment by tsepen** [comment]
Спасибо, работает

ср, 13 нояб. 2019 г., 20:10 Maksim Markelov <notifications@github.com>:
