### ISSUE TITLE
Несколько карт на одной странице

### ISSUE THREAD

**Issue by potapovnikita** [gribnoysup/react-yandex-maps#203]
Кто знает, подскажите, пожалуйста, как обеспечить загрузку нескольких карт на странице?
Добавляю например 5 карт, прогружается 2-3. Как-будто событие инициализации переписывается с каждой добавленной картой. Что-то успевает загрузиться, что-то нет. 
Заранее спасибо.

**Comment by gribnoysup** [comment]
Не воспроизводится. Приветик, пожалуйста, пример

**Comment by potapovnikita** [comment]
<img width="689" alt="Снимок экрана 2019-11-21 в 23 24 08" src="https://user-images.githubusercontent.com/20072877/69365536-623d7f00-0cb6-11ea-9339-e635688bbaba.png">
<img width="498" alt="Снимок экрана 2019-11-21 в 23 25 58" src="https://user-images.githubusercontent.com/20072877/69365570-771a1280-0cb6-11ea-84c0-0243aef8b8ab.png">

**Comment by gribnoysup** [comment]
На скриншоте видно что ошибка идет не из кода библиотеки, а из скрипта яндекс карт, проверьте какие `props` передаете в компоненты.

Как я уже сказал, без примера мало чем можно вам помочь.

Сама библиотека рендерит несколько карт на одном экране без проблем:

[![Edit sparkling-shadow-r0vqq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sparkling-shadow-r0vqq?fontsize=14&hidenavigation=1&theme=dark)
