### ISSUE TITLE
Broken route-editor example 

### ISSUE THREAD

**Issue by Menzorg** [gribnoysup/react-yandex-maps#212]
Здравствуйте. Спасибо за реакт реализацию. Толи я не правильно понимаю что должно происходить, толи на самом деле пример не работает. Ведь должен строиться маршрут а не просто два маркера ставиться?
https://react-yandex-maps.now.sh/controls/route-editor
А также в одном из исьюсов была ссылка на песочницу
https://codesandbox.io/s/kx805k12o3
Кажется тоже не работает, что тоже говорит что что-то сломалось.

**Comment by gribnoysup** [comment]
Привет @Menzorg! Если я правильно понимаю то Яндекс.Карты требуют [наличие API ключа](https://yandex.ru/blog/mapsapi/novye-pravila-dostupa-k-api-kart) при определенных запросах. У меня нет аккаунта в яндексе что бы получить данный ключ, но ты можешь создать себе свой и попробовать его подставить в пример в codesandbox

**Comment by Menzorg** [comment]
Благодраю за ответ. Я проверю это, и отпишусь по результату

**Comment by Menzorg** [comment]
Согласно новым правилам действительно и для платного и для бесплатного использования может требоваться ключ. А построение маршрута - является только платным функционалом, так что сходу проверить не могу, спасибо, исью себя исчерпало.
