### ISSUE TITLE
Карта не ререндерится при обновлении props

### ISSUE THREAD

**Issue by alexandergurkovdev** [gribnoysup/react-yandex-maps#218]
Есть app, в котором хранится state с координатами.
В app есть форма, которая по сабмиту отправляет fetch и получает данные, которые в т.ч. содержат координаты. Данные через props пробрасываю до карты.
Когда запрос уходит первый раз, карта рендерится и показывается нужный город, но при повторном запросе, когда обновляются props ререндера не происходит. В чем может быть проблема?
вот ссылка на репозиторий с проектом https://github.com/alexandergurkovdev/weather

**Comment by gribnoysup** [comment]
В этом коде координаты не передаются в `props` компонента `Map`, они передаются в `MapView` и никак не используются в дальнешейм. О том как передавать `props` в другие компоненты и как использовать их внутри компонентов можно почитать [в документации по React](https://ru.reactjs.org/docs/components-and-props.html)

**Comment by alexandergurkovdev** [comment]
а да, моя невнимательность). спасибо большое
