### ISSUE TITLE
Не отображается Placemark PieChart default#pieChart

### ISSUE THREAD

**Issue by c65c65** [gribnoysup/react-yandex-maps#219]
После указания iconLayout: 'default#pieChart' пропадает placemark, делал по песочнице: 
https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/layout.PieChart-docpage/
```

 <YMaps>
    <Map defaultState={{
      center: [55.751574, 37.573856],
      zoom: 9,
   }}
    >
      <Placemark geometry={[55.751574, 37.573856]}
        properties={{
          data: [
            { weight: 8, color: '#0E4779' },
            { weight: 100, color: '#1E98FF' },
            { weight: 4, color: '#82CDFF' }
          ],
          iconCaption: 'Диаграмма'
        }}
        options={{
          iconLayout: 'default#pieChart',
          iconPieChartRadius: 50,
          iconPieChartCoreRadius: 20,
          iconPieChartCoreFillStyle: '#ffffff',
          iconPieChartStrokeStyle: '#ffffff',
          iconPieChartStrokeWidth: 3,
          iconPieChartCaptionMaxWidth: 200
        }}
      />
    </Map>
  </YMaps>
```

**Comment by gribnoysup** [comment]
Модуль `layout.PieChart` не загружается по умолчанию, надо указать его как зависимость компонента Placemark. Про модульную систему в яндекс картах можно прочитать [в их документации](https://tech.yandex.ru/maps/jsapi/doc/2.1/dg/concepts/modules-docpage/), про то как это используется в `react-yandex-maps` можно прочитать [в документации к библиотеке](https://react-yandex-maps.now.sh/core-principles#modular-approach)
