### ISSUE TITLE
как передать apikey?

### ISSUE THREAD

**Issue by gagamil** [gribnoysup/react-yandex-maps#221]
Я делаю так: 
`<Map
          onLoad={ymaps => loadSuggest(ymaps)}
          modules={["SuggestView", "geocode"]}
          query={{ apikey: <MY_API_KEY>}}
        />`
Но при попытке использовать geocode получаю 403 Forbidden.
Полагаю дело в том, что в запросе нет моего ключа.
Подскажите, как его передать?
Спасибо

**Comment by gagamil** [comment]
Моя ошибка. Извините. Надо было YMaps инициализировать а не Map.

**Comment by relaxdd** [comment]
У меня наоборот. добавил ключ в YMaps а карта вообще перестала выводиться, странно как то
