### ISSUE TITLE
Need solution for render placemark balloon content

### ISSUE THREAD

**Issue by v2pwww** [gribnoysup/react-yandex-maps#23]
Need solution for rendering baloon content
i try make somethin like this
```
 <Placemark key={'placemark-' + uuid.v1()}
    geometry={{
        coordinates: [item.latitude, item.longitude],
    }}
    properties={{
        balloonContent: () => <span onClick={() => this.handleItemClick(item.id)}>item.name</span>,
        iconCaption: item.name
    }}
    options={{
        preset: 'islands#greenDotIconWithCaption',
        iconColor: '#aeca3b',
        controls: []
    }}
/>
```
but balloon content no rendering correctly

**Comment by gribnoysup** [comment]
Your `balloonContent` value is wrong. GeoObject `properties` props is just GeoObject `feature.properties` [from yandex.maps](https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/GeoObject-docpage/#param-feature.properties), it doesn't support React components.

This library doesn't support rendering React components GeoObject contents of any kind.

You could use [yandex.maps template factory](https://tech.yandex.com/maps/jsbox/2.1/placemark_balloon_layout) to create custom balloon layout and add your events to it.
