### ISSUE TITLE
Placemark, instanceRef called twice

### ISSUE THREAD

**Issue by Art-Mas** [gribnoysup/react-yandex-maps#230]
Hello. Actually, the title speaks for itself-instanceRef called twice. 
Here is an example: https://codesandbox.io/s/billowing-resonance-nub41
Maybe I'm doing something wrong?

**Comment by gribnoysup** [comment]
Thanks for reporting this issue, your code is totally fine! There was a bug in the library that is fixed in v4.4.0

**Comment by gribnoysup** [comment]
Keep in mind that in your particular example instanceRef can still be called twice as functions are created in the render method and thus they are not referentially equal. You can read more about how refs behave in React docs https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs
