### ISSUE TITLE
TypeError: ymaps.Style &&  ymaps.Panel is not a constructor

### ISSUE THREAD

**Issue by gudvinga** [gribnoysup/react-yandex-maps#233]
Спасибо за вашу работу, но у меня есть несколько проблем при загрузке модулей,
когда я делаю load: ['Style'] или load: ['Panel'], карта перестает отображаться, без этих модулей возникает ошибка TypeError: ymaps.Style &&  ymaps.Panel is not a constructor

Есть ли возможность использовать эти модули с react-yandex-maps или они сейчас не поддерживаются?

**Comment by gribnoysup** [comment]
Привет! Приведи пожалуйста пример кода который вызывает ошибку

**Comment by gudvinga** [comment]
https://codesandbox.io/s/gracious-ganguly-uqsdo?file=/src/App.js

**Comment by mmarkelov** [comment]
@gudvinga `ymaps.Style`, модуль который был доступен в первой версии карт. По `Panel` сказать не могу. Но насколько я помню в базовых модулях он тоже не встречается. Может у Вас есть ссылка на работающий пример в песочнице Яндекс карт?

**Comment by gudvinga** [comment]
@mmarkelov https://tech.yandex.ru/maps/jsbox/2.1/sidebar пример в sidebar в песочнице

**Comment by mmarkelov** [comment]
@gudvinga перенес пример на `react-yandex-maps`. Надеюсь поможет понять основную идею:
https://codesandbox.io/s/wispy-shape-4rr0p?file=/src/App.js

**Comment by gudvinga** [comment]
@gribnoysup @mmarkelov спасибо огромное, извините, что отнял ваше время
