### ISSUE TITLE
Как получить меняющийся массив объектов в кластере?

### ISSUE THREAD

**Issue by OlgaDorofeeva** [gribnoysup/react-yandex-maps#234]
Добрый день! У меня есть несколько точек, в каждой из которых есть какой-то товар. И когда карта при зуме уменьшается и они объединяются в кластер, то возле кластера нужно показывать наименьшую цену товара из всех точек, входящих в этот кластер на данный момент. 
Кластер создавался через createClass. В build() можно получить массив из координат тех точек, которые объединяются. И если их количество меняется, то этот массив тоже меняется, и минимальная цена из этого массива тоже высчитывается и меняется. Но если попытаться отправить эту минимальную цену в state, сразу появляется ошибка TypeError: Cannot read property 'destroy' of undefined.  

Подскажите, пожалуйста, если не так, то как можно вне createClass получить координаты точек, объединяемых в кластер, и чтобы при изменении количества этих точек, массив из координат тоже менялся? Если пробовать ref, то массив отображается только один раз при загрузке карты,  и не меняется больше. 

https://codesandbox.io/s/gracious-jang-1vidz?file=/src/App.js

**Comment by mmarkelov** [comment]
@OlgaDorofeeva привет) Я предлагаю находить минимальную цену вне `templateLayoutFactory`. Иначе достаточно сложно будет соединить логику реакта и апи яндекса. У меня пока нет идей как инициализировать цену, да и привязка к изменения карты выглядит костыльно, но предлагаю пока отталкиваться от этого)

https://codesandbox.io/s/romantic-neumann-ck5zg?file=/src/App.js

**Comment by OlgaDorofeeva** [comment]
Спасибо огромное за помощь!

**Comment by mmarkelov** [comment]
@OlgaDorofeeva если не разберетесь, то попробую посмотреть еще, возможно есть более простой способ) Спасибо!

**Comment by OlgaDorofeeva** [comment]
@mmarkelov, не разобралась, к сожалению. Если у вас будет возможность, посмотрите, пожалуйста. При загрузке вообще толком никаких данных получить не выходит

**Comment by mmarkelov** [comment]
@OlgaDorofeeva обновил песочницу https://codesandbox.io/s/romantic-neumann-ck5zg?file=/src/App.js

Переместил логику установки цены в метод `createCluster` кластера, и в нем обновляю стейт, все еще не уверен, что это оптимальный способ

**Comment by OlgaDorofeeva** [comment]
@mmarkelov, о, огромное спасибо, до этого бы точно сама не додумалась!
