### ISSUE TITLE
Как получить доступ к YMaps.GeoCoordSystem

### ISSUE THREAD

**Issue by nazarukroman** [gribnoysup/react-yandex-maps#241]
Здравствуйте, не могу понять как получить доступ к [YMaps.GeoCoordSystem](https://tech.yandex.ru/maps/archive/doc/jsapi/1.x/ref/reference/geocoordsystem-docpage/) с помощью `withYMaps` `HOC`. Вероятно я неправильно указываю имя модуля? Мне нужен метод `distance`, чтобы найти расстояние между двумя точками.

Подскажите, пожалуйста, как достучаться до метода `distance`.

https://codesandbox.io/s/react-yandex-map-wefcf

**Comment by mmarkelov** [comment]
@nazarukroman этот модуль был доступен в первой версии карт. Сейчас он переехал в [`coordSystem.geo`](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/coordSystem.geo-docpage/)
```js
import React from "react";
import {
  FullscreenControl,
  Map as YMap,
  withYMaps,
  ZoomControl,
  Placemark
} from "react-yandex-maps";

function MapContentComponent(props) {
  const { ymaps, points } = props;

  // distance -> getDistance
  console.log(ymaps.coordSystem.geo.getDistance(points[0], points[1]));

  return (
    <YMap
      defaultState={{
        center: [59.9375, 30.308611],
        zoom: 9
      }}
    >
      <>
        {points.map((point, index) => (
          <Placemark key={index} defaultGeometry={point} />
        ))}
      </>

      <FullscreenControl />
      <ZoomControl />
    </YMap>
  );
}

export const MapContent = withYMaps(MapContentComponent, true, [
  "coordSystem.geo"
]);
```

**Comment by nazarukroman** [comment]
@mmarkelov Спасибо! А где можно посмотреть как правильно именовать модули для доступа к АПИ?

**Comment by mmarkelov** [comment]
@nazarukroman можно посмотреть [здесь](https://tech.yandex.ru/maps/doc/jsapi/2.1/dg/concepts/modules-docpage/)

**Comment by nazarukroman** [comment]
Возможно я в прошлый раз смотрел другую версию АПИ, спасибо, я получил ответ :)
