### ISSUE TITLE
Не отображаются карты в браузере Safari

### ISSUE THREAD

**Issue by Adigezalov** [gribnoysup/react-yandex-maps#242]
В Safari по какой-то причине карты не отображаются.
Кто-нибудь сталкивался с этой проблемой?

**Comment by mmarkelov** [comment]
@Adigezalov привет! Очень абстрактная проблема. Без дополнительной информации невозможно сказать, что может быть не так.

**Comment by Adigezalov** [comment]
@mmarkelov Привет!
Например код:
`
<YMaps>
          <Map
            width={"100%"}
            height={"100%"}
            state={{
              center: [latitude, longitude],
              zoom: 16,
            }}
          >
            <Placemark
              geometry={[latitude, longitude]}
            />
          </Map>
        </YMaps>
`
Отлично работает в браузерах android, но если запустить на ios в safari, то просто пустой экран...
Если запускать на десктопном safari, то так же белый экран

**Comment by gribnoysup** [comment]
@Adigezalov без настоящего примера где ошибка воспроизводится тебе вряд ли кто-то сможет помочь. В Safari карты на сайте с документацией грузятся без ошибок так что проблема скорее всего где-то в твоем коде.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5036933/85322682-01ce2480-b4c7-11ea-9a11-d75c415e238e.png">

**Comment by Adigezalov** [comment]
Извиняюсь, это была моя ошибка, неправильно сработал с flex 🥴
