### ISSUE TITLE
Тестирование карты

### ISSUE THREAD

**Issue by azuevcode** [gribnoysup/react-yandex-maps#243]
Добрый день. Есть какие-то способы протестировать карту и ее содержимое через jest-enzyme? Пишу на typescript. Есть кастомные контролы, которые могут изменять зум и центр карты через стейт, также имеется LoadingObjectManager (все это children внутри Map), но ничего из этого не могу протестировать

**Comment by gribnoysup** [comment]
Нет. Для того что бы карта работала нужно что бы браузер подгрузил API Яндекс.Карт. Для этого нужно настоящее браузерное окружение, а не `jsdom` который по дефолту использует `jest`.
