### ISSUE TITLE
Search doesn't work anymore

### ISSUE THREAD

**Issue by evgtretyakov** [gribnoysup/react-yandex-maps#245]
![Screenshot_69](https://user-images.githubusercontent.com/51711617/85403737-8cb22c00-b566-11ea-8941-46e89b602ec7.jpg)
Some problems with search. Is it about apikey?

**Comment by mmarkelov** [comment]
@evgtretyakov yeah! This is about API Key

**Comment by evgtretyakov** [comment]
can I change it anywhere?

**Comment by mmarkelov** [comment]
@evgtretyakov you can get key [here](https://developer.tech.yandex.ru/)

And then you should define it in `YMpas`:
```js
<YMaps query={{ apikey: 'Your key here' }}>
  ...
</YMaps>
```

**Comment by evgtretyakov** [comment]
thank you much, just like here:
https://react-yandex-maps.now.sh/provider-consumer/ymaps-provider-component
