### ISSUE TITLE
Как сделать анимацию движения объектов на карте?

### ISSUE THREAD

**Issue by taskway** [gribnoysup/react-yandex-maps#246]
На чистом JS получается сделать анимацию движения объекта по карте используя класс расширяющий GeoObject. Пример анимации: https://codesandbox.io/s/beautiful-paper-dvoho

На React JS не получилось. Пример кода: https://codesandbox.io/s/summer-river-dirjl

**Comment by mmarkelov** [comment]
@taskway получилось сделать. Но честно говоря, не очень красиво
https://codesandbox.io/s/broken-glade-b7pfn?file=/index.js

**Comment by taskway** [comment]
@mmarkelov Спасибо! Вариант хороший!
