### ISSUE TITLE
this.toGlobalPixelBounds is not a function

### ISSUE THREAD

**Issue by nazarukroman** [gribnoysup/react-yandex-maps#247]
Здравствуйте, использую метод `getCenterAndZoom` из `util.bounds`, но получаю такую ошибку `this.toGlobalPixelBounds is not a function`.

Может кто-нибудь подсказать в чем проблема?

Пример:
https://codesandbox.io/s/react-yandex-map-wefcf

**Comment by mmarkelov** [comment]
@nazarukroman думаю что проблема с контекстом вызова функции(**this**)
**MapContentComponent**:
```js
const getCenterAndZoom = ymaps.util.bounds.getCenterAndZoom

// В данном случае this будет указывать на React компонент
const centerAndZoom = getCenterAndZoom(
    [[59.893177, 30.300489], [60.014985, 30.464908]],
    [320, 240]
  );
``` 

Есть два варианта чтобы Ваш код заработал:

- Вызвать метод напрямую
```js
const centerAndZoom = ymaps.util.bounds.getCenterAndZoom(
    [[59.893177, 30.300489], [60.014985, 30.464908]],
    [320, 240]
  );
```

- Привязать **this**
```js
const getCenterAndZoom = ymaps.util.bounds.getCenterAndZoom.bind(
    ymaps.util.bounds
  );

const centerAndZoom = getCenterAndZoom(
    [[59.893177, 30.300489], [60.014985, 30.464908]],
    [320, 240]
  );
```

**Comment by nazarukroman** [comment]
Ох, точно, я совсем забыл про это :(
Спасибо большое за ответ!
