### ISSUE TITLE
Adding yandex plugin

### ISSUE THREAD

**Issue by Shokhrukh2606** [gribnoysup/react-yandex-maps#248]
Hello! I want to connect this [plugin](https://github.com/yandex/mapsapi-area), can i connect, if i can you provide example, or should i use turf?

**Comment by mmarkelov** [comment]
@Shokhrukh2606 you can check https://codesandbox.io/s/blissful-monad-3m03q?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js
