### ISSUE TITLE
Не работает enterprise версия с ключом API

### ISSUE THREAD

**Issue by XanderSpecter** [gribnoysup/react-yandex-maps#252]
Доброго времени суток. Проблема следующая: использую обёртку
`<YMaps
                    enterprise
                    query={{
                        apikey: 'some-api-key',
                    }}
                >`

Внутри используется компонент-обёртка для Map с некоторым стейтом, которая обёрнута в withYMaps с пробросом geocode

Соответственно, внутри этой обёртки происходят действия с API geocode.

Пробовал использовать без ключа и без флага enterprise - карта работает, но обращений к API возвращали 403 - в итоге я сделал вывод, что нужен ключ (чудеса дедукции)

Но когда я добавил флаг enterprise и ключ, карта вообще перестала отображаться и сам компонент не рендерится в DOM в принципе. При этом никаких сообщений об ошибках не было.

Стоит отметить, что ключ я получил от заказчика "как есть" и у меня нет сейчас способов удостовериться в его корректности. Полагаю, копать надо в сторону ключа? Там должен быть какой-то лист доступа? И, если да, то как туда добавить доступ для разработки локально?

**Comment by mmarkelov** [comment]
@XanderSpecter ну во-первых **entrerpise** вроде как бесполезно передавать, `YMaps` его проигнорирует.
У меня есть предположение что проблема в обертке над **Map**. Поэтому было бы неплохо увидеть его. Будет идеально если получится собрать демо на [codesandbox](https://codesandbox.io/). У меня вроде есть ключ, попробую тогда разобраться в чем может быть проблема

**Comment by XanderSpecter** [comment]
@mmarkelov там в обёртке пока ничего и нет, кроме возврата Map с точкой, ибо я как бы и застопорился на моменте с рендером карты и ничего написать ещё не успел :) Был только тестовый запрос к API. https://codesandbox.io/s/ymaps-nimyj - вот тут пример того, как я это использую (обёртка перенесена целиком, а из родителя только для карт). Я полагаю, что дело всё таки в самом ключе, так как к апи уходит один запрос, который получает ответ со статусом 200, но в теле ответа ошибка 403. Так что вопрос, вероятно, скорее про управление доступом в кабинете разработчика, так как я с ним не знаком и у меня нет доступа к этому кабинету. Заодно хотелось бы понять, можно ли настроить доступ с локального компа.

**Comment by gribnoysup** [comment]
@mmarkelov `enterprise` поддерживается, все норм 😉 

https://github.com/gribnoysup/react-yandex-maps/blob/1fc645cc27c89c87a70ce09b70c64f1561774a87/src/Provider.js#L32

@XanderSpecter я бы предложил вам сначала проверить ключ, можете попробовать сделать такой же простой пример но без Реакт обертки а напрямую с яндексовским апи, если видите ту же ошибку, то проблема почти абсолютно точно с ключом

**Comment by mmarkelov** [comment]
@XanderSpecter попробовал со своим ключом - проблем нет
https://codesandbox.io/s/ymaps-2zbri?file=/src/YandexMap.jsx

**Comment by XanderSpecter** [comment]
@mmarkelov значит и правда надо с ключом разбираться, спасибо)
