### ISSUE TITLE
Получение текущего zoom 

### ISSUE THREAD

**Issue by MrNapcae** [gribnoysup/react-yandex-maps#259]
Добрый день, не могу получить изменения параметра zoom (в yandex api есть метод getZoom (https://tech.yandex.ru/maps/archive/doc/jsapi/1.x/dg/concepts/map-parameters-docpage/)) как реализовать чтобы получить значение?
Через withYMaps не получилось....

**Comment by mmarkelov** [comment]
@MrNapcae привет. Нужно вызвать метод **getZoom** у инстанса карты:

```js
       const getZoom = () => {
           if (mapRef.current) {
               console.log(mapRef.current.getZoom());
           }
       }

       <Map
          ...
          instanceRef={(ref) => {
            if (ref) mapRef.current = ref;
          }}
        >
```

**Comment by MrNapcae** [comment]
@mmarkelov Спасибо! Работает, еще вопрос пишет что нет метода: (https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/ICoordSystem-docpage/#method_detail__getDistance)
Ошибка: TypeError: Cannot read property 'geo' of undefined

 <Map
          ...
  instanceRef={ref => {
              if (ref) mapRef = ref
            }}
>

  const getZoom = () => {
    const map = mapRef.getBounds()

    console.log(mapRef.coordSystem.geo.getDistance(map[0][0], map[0][1]))
  }
