### ISSUE TITLE
Кластеры в ObjectManager

### ISSUE THREAD

**Issue by vyudrozd** [gribnoysup/react-yandex-maps#260]
Я использую кластеризацию через ObjectManager:

```javascript
<ObjectManager
	instanceRef={obj => (objectManagerRef.current = obj)}
	options={{
		clusterize: true,
		gridSize: 32,
		}}
	objects={{
		preset: 'islands#greenDotIcon',
		}}
	clusters={{
		preset: 'islands#greenClusterIcons',
		}}
		features={data}
		onClick={handleClick}
	/>
```

В данном примере, data - это данные загружаемые с сервера. На странице, где я использую Manager, есть фильтры, которые контролирует массив data, который подгружается с сервера. Проблема происходит на этапе, когда я начинаю переключать фильтры и, соответсвенно, менять data: кластеры, которые генерирует Manager записывают не только данные, которые находятся в данный момент в data, а также и старые данные. Таким образом число данных в кластерах растет. Кроме того, некоторые кластеры появляются из ничего по тому же принципу. Пример до включения и выключения фильтра и после: 
![Снимок экрана 2020-09-14 в 12 17 45](https://user-images.githubusercontent.com/44552051/93067803-57f4d300-f684-11ea-8359-f0a71dff7adb.png)
![Снимок экрана 2020-09-14 в 12 19 18](https://user-images.githubusercontent.com/44552051/93067974-8c688f00-f684-11ea-8501-d37ed6845cb8.png)

Пробовал решать эту проблему используя фильтры в самом Manager, а также фильтруя данные локально, однако данные решения ломали карту еще больше. Можно ли решить данную проблему используя ObjectManager?

**Comment by mmarkelov** [comment]
@vyudrozd сложно помочь Вам без кода. Если есть возможность, то пример вашего кода на [codesandbox](https://codesandbox.io/) очень бы помог

**Comment by vyudrozd** [comment]
Проблема была не в библиотеке, а в моем неполном понимании устройства карты, с сервера приходили точки с одинаковыми id. Разобрался пока пытался написать код на codesandbox
