### ISSUE TITLE
Не работает метод getDistance

### ISSUE THREAD

**Issue by MrNapcae** [gribnoysup/react-yandex-maps#261]
Не работает метод getDistance после вызова по координатам возвращает `NaN` вызов:
```js
console.log(ymaps.coordSystem.geo.getDistance([55.908244601861], [37.8609543186403]))
```

**Comment by mmarkelov** [comment]
@MrNapcae вы передаете невалидные данные, так что это ожидаемый результат. Вы должны передавать ширину и долготу.
```js
ymaps.coordSystem.geo.getDistance([55.654884,37.527034], [55.767305,37.976100])
```
