### ISSUE TITLE
TypeSelector mapTypes

### ISSUE THREAD

**Issue by kvrvgixzis** [gribnoysup/react-yandex-maps#267]
Если пишу какой-либо тип отличный от yandex#map - карта ломается и страница не загружается. Это какие-то ограничения по апи, или нужно акк-то по особенному их загрузить. Не разобрался

**Comment by mmarkelov** [comment]
@kvrvgixzis должно работать. Трудно сказать в чем может быть ошибка без примера кода.
```js
        const mapState = { center: [55.76, 37.64], zoom: 10, type: "yandex#hybrid" };

        <YMaps>
          <Map state={mapState} />
        </YMaps>
```

**Comment by kvrvgixzis** [comment]
убрал apikey и заработало, спасибо
