### ISSUE TITLE
Анимация изменения zoom карты со своими кнопками

### ISSUE THREAD

**Issue by aspirin-vd** [gribnoysup/react-yandex-maps#268]
Как изменять zoom своими кнопками и при этом что бы была анимация как при нажатии на стандартные кнопки?
Пример react api: https://yandex.com/dev/maps/jsbox/2.1/zoom_layout

**Comment by mmarkelov** [comment]
@aspirin-vd как-то так:
```js
export default function App() {
  const [zoom, setZoom] = useState(9);

  return (
    <div>
      <YMaps>
        <Map state={{ center: [55.751574, 37.573856], zoom }} />
      </YMaps>
      <div>
        <button onClick={() => setZoom(zoom + 1)}>Zoom in</button>
        <button onClick={() => setZoom(zoom - 1)}>Zoom out</button>
      </div>
    </div>
  );
}
```

**Comment by aspirin-vd** [comment]
> @aspirin-vd как-то так:
> 
> ```js
> export default function App() {
>   const [zoom, setZoom] = useState(9);
> 
>   return (
>     <div>
>       <YMaps>
>         <Map state={{ center: [55.751574, 37.573856], zoom }} />
>       </YMaps>
>       <div>
>         <button onClick={() => setZoom(zoom + 1)}>Zoom in</button>
>         <button onClick={() => setZoom(zoom - 1)}>Zoom out</button>
>       </div>
>     </div>
>   );
> }
> ```

У меня на данный момент так реализовано, но анимации отдаления и приближения карты нет, а хотелось бы её добавить

**Comment by mmarkelov** [comment]
@aspirin-vd я вас понял. Придется тогда так:
```js
export default function App() {
  const map = React.useRef(null);
  const [zoom, setZoom] = useState(9);

  useEffect(() => {
    if (map.current) {
      map.current.setZoom(zoom, { duration: 300 });
    }
  }, [zoom]);

  return (
    <div>
      <YMaps>
        <Map
          instanceRef={map}
          onBoundsChange={(e) => {
            if (e.get("newZoom") !== e.get("oldZoom")) {
            }
          }}
          defaultState={{ center: [55.751574, 37.573856], zoom: 9 }}
        />
      </YMaps>
      <div>
        <button onClick={() => setZoom(zoom + 1)}>Zoom in</button>
        <button onClick={() => setZoom(zoom - 1)}>Zoom out</button>
      </div>
    </div>
  );
}
```

**Comment by aspirin-vd** [comment]
Благодарю
