### ISSUE TITLE
Как сделать поиск по своим точкам?

### ISSUE THREAD

**Issue by Selivaniuk** [gribnoysup/react-yandex-maps#270]
У меня есть несколько Placemark, как я могу сделать поиск по ним через SearchControl?

**Comment by mmarkelov** [comment]
Ваш пример кода на [codesandbox](https://codesandbox.io/), либо пример из песочницы Яндекс.карт может ускорить процесс получения помощи

**Comment by mmarkelov** [comment]
@Selivaniuk ответил Вам в https://github.com/gribnoysup/react-yandex-maps/issues/236
Если будут проблемы откройте эту ишью
