### ISSUE TITLE
change the array Placemarks rendered

### ISSUE THREAD

**Issue by aldeimos** [gribnoysup/react-yandex-maps#272]
I have an array. After some actions, my array can changes and at this point map totally breaks (points doesnt rendered or one point stick at the map center. How can i dynamically change my state-array and rerender Map?

**Comment by aldeimos** [comment]
Ремарка для тех, у кого точно так же плохо, как и у меня. Я хочу при изменении стейта массива, по которому я рисую Placemark чистить текущие Placemark и рисовать новые, по новому стейту. Сейчас при изменении стейта карта начинает ломаться

**Comment by mmarkelov** [comment]
@aldeimos без примера не могу сказать, что не так. Собрал небольшое [демо](https://codesandbox.io/s/naughty-maxwell-le0gj?file=/src/App.js), никаких проблем при изменении стейта не заметил

**Comment by tilvan** [comment]
Прошу прощения. Имею похожую проблему.
При изменении массива салонов из одного элемента не рендерится метка.
`
const [featureCollection, setFeatureCollection] = useState<any>();
...
const prepareOMFeatures = useCallback((): void => {
    const features: any = [];
    let currentPlacemarkCoordinates = null;

    salonsList.map((salonItem, index) => {
      const coordinates = [salonItem.geoLat, salonItem.geoLon];
      const salonRating = salonItem.rating ? salonItem.rating.overall : '';
      const listId = salonItem.listId ? [...salonItem.listId] : [salonItem.id];

      features.push({
        type: 'Feature',
        id: index,
        geometry: {
          type: 'Point',
          coordinates,
        },
        properties: {
          openBalloonOnClick: false,
          hintContent: salonItem.name,
          iconContent: salonRating,
          listId,
        },
        options: {
          iconLayout: 'default#imageWithContent',
          iconImageHref: mapPin,
          iconImageSize: [35, 40],
          iconImageOffset: [-17, -20],
          iconContentOffset: [5, 5],
          iconContentLayout: iconContentTemplate.current,
        },
      });

      currentPlacemarkCoordinates = coordinates;

      return salonItem;
    });

    const collection = {
      type: 'FeatureCollection',
      features,
    };

    setFeatureCollection(collection);
  }, [iconContentTemplate, salonsList]);
...
<YMaps>
        <Map
          height={mapHeight}
          defaultState={mapState}
          className={cx(styles.mapContainer, mapContainerClassName)}
          onLoad={handleMapLoad}
          instanceRef={(ref): void => {
            mapRef.current = ref;
          }}
          modules={[
            'templateLayoutFactory',
            'layout.ImageWithContent',
            'geocode',
          ]}
          onBoundsChange={handleBoundsChange}
        >
          <ZoomControl
            options={{ position: { right: 10, top: 100, bottom: 'auto' } }}
          />

          {featureCollection && (
            <ObjectManager
              instanceRef={(ref): void => {
                objectManagerRef.current = ref;
              }}
              options={{
                clusterize: true,
                gridSize: 32,
                ...objectManagerOptions,
              }}
              objects={{
                openBalloonOnClick: false,
              }}
              clusters={{
                preset: 'islands#redClusterIcons',
              }}
              features={featureCollection}
              onClick={handlePlacemarkClick}
            />
          )}
        </Map>
      </YMaps>`
      
      @mmarkelov с удовольствием посмотрел бы пример из комментария выше, но он уже недоступен по ссылке.
