### ISSUE TITLE
Кластер с visible: false, появляется после зума

### ISSUE THREAD

**Issue by Spaider15** [gribnoysup/react-yandex-maps#274]
https://codesandbox.io/s/muddy-lake-b2uzq

Через секунду кластеру выставляется опция `visible: false`
Но если карту приблизить или отдалить, он снова появляется. С точками такой проблемы нет.

**Comment by mmarkelov** [comment]
@Spaider15 у меня только вопрос почему передача свойства `visible` скрывает кластер. В [доке](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/Clusterer.html#Clusterer__param-options) Яндекс карт у Кластера нет такого свойства.
Я не знаю Ваш кейс, но думаю, можно попробовать так:
```js
<Map defaultState={{ center: [55.72, 37.44], zoom: 10 }}>
        {visible && (
          <Clusterer
            options={{
              preset: "islands#invertedVioletClusterIcons",
              groupByCoordinates: false
            }}
          >
            {points.map((coordinates, index) => (
              <Placemark
                key={index}
                geometry={coordinates}
                // options={{ visible }}
              />
            ))}
          </Clusterer>
        )}
      </Map>
```

**Comment by Spaider15** [comment]
Нашел другой способ, про этот способ я тоже знал, но он более "лагучий", чем скрытие через visible, закрываю, спасибо!
