### ISSUE TITLE
[ERROR][BLOCK] Ошибка с загрузкой Яндекс карт

### ISSUE THREAD

**Issue by nagayev** [gribnoysup/react-yandex-maps#276]
Сегодня на своем сайте не увидел Яндекс карту. Подумал, что что-то сломал, но оказалось, что проблема есть и в стабильной версии на сайте.
В консоли пишет:
```
Uncaught TypeError: o is null
    ymapsInit https://api-maps.yandex.ru/2.1/?onload=__yandex-maps-api-onload__$$1epjdprc7&onerror=__yandex-maps-api-onerror__$$1epjdprc7&lang=ru_RU&load=&ns=&mode=release:1
    <anonymous> https://api-maps.yandex.ru/2.1/?onload=__yandex-maps-api-onload__$$1epjdprc7&onerror=__yandex-maps-api-onerror__$$1epjdprc7&lang=ru_RU&load=&ns=&mode=release:1
```
Версия react-yandex-maps: 4.5.0
В 4.6.0 так же исправления нет.

**Comment by mmarkelov** [comment]
@nagayev подтверждаю. Похоже какие-то проблемы с последней версией карт.
Постараюсь решить ASAP. Workaround:

```js
<YMaps version="2.1.77">
```

**Comment by mmarkelov** [comment]
Баг со стороны разрабов яндекс карт!
```js
...
var o = t.env.namespace ? t.utils.accessDeep(n, t.env.namespace) : null;
    // Возможное обращение к **null**
    o.parent[o.name] && o.parent[o.name].modules && o.parent[o.name].ready && console.error("(Yandex Maps JS API): api is already enabled on this page with same namespace."),
...
```

**Comment by nagayev** [comment]
@mmarkelov Окей, спасибо за временное решение.

**Comment by mmarkelov** [comment]
@nagayev нашел еще вариант.
```js
<YMaps query={{ ns: "ymaps" }}>
```

**Comment by mmarkelov** [comment]
Также советую следить за текущесь ситуацией [здесь](https://yandex.ru/blog/mapsapi/pereklyuchenie-ssylki-2-1-na-versiyu-2-1-78#comment-add)

**Comment by nagayev** [comment]
@mmarkelov Окей.

**Comment by nagayev** [comment]
Все заработало, Яндекс починил на своей стороне.
Закрываю.
