### ISSUE TITLE
[Question] Геокодер

### ISSUE THREAD

**Issue by nagayev** [gribnoysup/react-yandex-maps#277]
Очень хочу использовать геокодер, но он платный.
Как можно решить эту проблему?
Может быть встроить в эту библиотеку альтернативный геокодер(ы) или это не входит в задачи этого проекта?
Поискал open street map for react, что-то не нашел.

**Comment by mmarkelov** [comment]
@nagayev полагаю что никак. Вы можете посмотреть [условия использования](https://yandex.ru/dev/maps/geocoder/).
По поводу бесплатных решений [есть](https://github.com/PaulLeCam/react-leaflet)

**Comment by nagayev** [comment]
@mmarkelov Спасибо.
