### ISSUE TITLE
Failed prop type: Invalid prop `children` supplied to `YMaps`, expected a ReactNode.

### ISSUE THREAD

**Issue by Fi1osof** [gribnoysup/react-yandex-maps#28]
Сергей, добрый день!

Спасибо за отличный компонент! 
Все здорово, но мелкая неприятность есть. На сколько я понимаю, в YMaps можно передавать функцию-обертку, вот здесь прописано. https://github.com/gribnoysup/react-yandex-maps/blob/master/src/YMaps.js#L62-L64
Я делаю так:
```
render(){

	return <YMaps
		children={function(yamaps){return <AutoComplete 
			yamaps={yamaps}
		/>}}
	>
  </YMaps>;
}
```
Но в консоли ловлю предупреждение "Failed prop type: Invalid prop `children` supplied to `YMaps`, expected a ReactNode.", хотя рендерится то, что я хочу - то есть компонент с переданным в него АПИ. Судя по всему, проптайпс недописан, протисана только нода. https://github.com/gribnoysup/react-yandex-maps/blob/master/src/YMaps.js#L10

Спасибо!

**Comment by gribnoysup** [comment]
@Fi1osof привет!

Да, забыл поправить propTypes когда добавил новое API, спасибо что заметил. Хочешь сделать пулл-реквест с фиксом? Если нет, все ок, я поправлю сам как будет время

**Comment by Fi1osof** [comment]
Честно сказать, я пока еще не очень силен в проптипах (плюс не в курсе всех зависимостей), так что лучше, если сам пропишешь, а я посмотрю как правильно :)
Спасибо!

**Comment by gribnoysup** [comment]
Пофикшено в новом релизе https://github.com/gribnoysup/react-yandex-maps/releases/tag/v2.1.0

**Comment by Fi1osof** [comment]
Спасибо!
