### ISSUE TITLE
Как сделать поиск адресов лишь по москве?

### ISSUE THREAD

**Issue by denibudeyko** [gribnoysup/react-yandex-maps#282]
Добрый день, использую модуль SuggestView для адресов. Каким образом можно сделать что бы результаты выдачи были ограниченны лишь Москвой ? Доставка лишь по Москве

**Comment by mmarkelov** [comment]
@denibudeyko насколько я знаю это возможно лишь с использованием опции [boundedBy](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/suggest.html#suggest__param-options.boundedBy)
