### ISSUE TITLE
Is it possible to add styles to Balloon?

### ISSUE THREAD

**Issue by adelinyshka** [gribnoysup/react-yandex-maps#286]
Hi :relaxed:
I check [documentation](https://yandex.ru/dev/maps/jsbox/2.1/balloon_autopan) for Yandex Maps API, so there is possible to style Balloon, is it possible also in react-yandex-maps?

I just need rounded corners of Balloon

Thank you)

**Comment by mmarkelov** [comment]
hello, @adelinyshka!
Of course you can use `templateLayoutFactory` like in your provided example, but i suppose it will quite complicated, cause you will need to control balloon logic and its styling by yourself. If you just need rounded corners you can use some hacky solution that should help:
```css
[class*="-balloon"] {
  border-radius: 6px;
}
```

**Comment by adelinyshka** [comment]
> ```css
> [class*="-balloon"] {
>   border-radius: 6px;
> }
> ```


Yeap! Thats works! U r amazing! Thx a lot for promt reply!
:heart:
