### ISSUE TITLE
Собственный макет балуна кластера

### ISSUE THREAD

**Issue by gadzhimari** [gribnoysup/react-yandex-maps#287]
Пытаюсь задать собственный макет балуна для кластера на Яндекс Картах. Делал по аналогии с примерами описанными в доке https://yandex.ru/dev/maps/jsbox/2.1/cluster_custom_balloon_content_layout/, но панель при клике на балун кластера все равно отображается.

Пробовал задавать опции для кластера и с префиксом cluster и без, но панель все равно отображается.

Набросал пример [codesandbox,](https://codesandbox.io/s/eager-forest-is0tz?file=/src/YMap.js) на мб у кого-нибудь есть какие-нибудь догадки, что не так.

![2021-02-10_10-00-36](https://user-images.githubusercontent.com/1849608/107477872-9b972e80-6b89-11eb-86b5-a5db1fb1283d.png)

**Comment by mmarkelov** [comment]
@gadzhimari поправил вашу [песочницу](https://codesandbox.io/s/muddy-currying-jfzem?file=/src/YMap.js), оставил в ней комментарии что было не так

**Comment by gadzhimari** [comment]
Да точно. Я эту проблему решил при помощи hoc-а withYMaps.
