### ISSUE TITLE
Как сделать режим навигатора при клике кнопку с текущим местоположением

### ISSUE THREAD

**Issue by gadzhimari** [gribnoysup/react-yandex-maps#291]
Можно ли в принципе при клике на точку с моим текущим местоположением сделать постоянно обновляемой для возможности постоянного трекинга того, где я в данный момент нахожусь. Типа что-то похожее на навигатор. Если способ как-то достучаться до точки "Я" на карте?
![2021-03-02_22-37-39](https://user-images.githubusercontent.com/1849608/109706239-c33a4f00-7ba9-11eb-9743-f45649b8c620.png)

**Comment by mmarkelov** [comment]
@gadzhimari привет! Не уверен что апи Яндекс карт позволяет трекать позицию пользователя. Возможно можно использовать `setInterval`, но я крайне не уверен что это законно) И лучше так не делать. Как вариант можно попробовать [`watchPosition`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition):
```js
useEffect(() => {
    const success = ({ coords }) => {
      const { latitude, longitude } = coords;
      setCoords([latitude, longitude]);
    };

    const error = (err) => {
      console.warn(err.message);
    };

    const options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };

    const id = navigator.geolocation.watchPosition(success, error, options);

    return () => {
      navigator.geolocation.clearWatch(id);
    };
  }, []);
```
