### ISSUE TITLE
Построение маршрута из нескольких точек В в одну точку А

### ISSUE THREAD

**Issue by Skaipia** [gribnoysup/react-yandex-maps#296]
Здравствуйте, подскажите, пжл, мне нужно проложить маршрут от нескольких точек (например из 2 близких станций метро в один ТЦ), у Яндекс API есть из похожего multiRouter, у react-yandex-maps как я понимаю нет чего то похожего? или я плохо искала?
![image](https://user-images.githubusercontent.com/23311577/110829101-cec3ff00-82a8-11eb-9ca1-22cc026dd6c0.png)

**Comment by mmarkelov** [comment]
@Skaipia привет! По маршрутизации было открыто несколько issue, к примеру #14, #68 
`react-yandex-maps` всего лишь обертка над Яндекс картами, так что, все что есть в яндекс картах вы можете использовать. Простой пример маршрута:
```js
export default function App() {
  const map = useRef(null);
  const mapState = {
    center: [55.739625, 37.5412],
    zoom: 12
  };

  const addRoute = (ymaps) => {
    const pointA = [55.749, 37.524];
    const pointB = "Москва, Красная площадь";

    const multiRoute = new ymaps.multiRouter.MultiRoute(
      {
        referencePoints: [pointA, pointB],
        params: {
          routingMode: "pedestrian"
        }
      },
      {
        boundsAutoApply: true
      }
    );

    map.current.geoObjects.add(multiRoute);
  };

  return (
    <div className="App">
      <YMaps query={{ apikey }}>
        <Map
          modules={["multiRouter.MultiRoute"]}
          state={mapState}
          instanceRef={map}
          onLoad={addRoute}
        ></Map>
      </YMaps>
    </div>
  );
}
```

Учтите что для построения маршрутов у вас должен быть ключ разработчика

**Comment by Skaipia** [comment]
Спасибо, разобралась

**Comment by Shakxzod-Namazbaev** [comment]
Thank you for example!
