### ISSUE TITLE
Проблема с полигоном

### ISSUE THREAD

**Issue by bramov** [gribnoysup/react-yandex-maps#297]
Здравствуйте, заметил довольно странное поведение - если зумить карту с большим полигоном, то он дублируется разными размерами. 

Пример кода вот здесь: https://github.com/bramov/react-yamps-polygons/blob/master/src/App.js
Пощупать можно тут: https://bramov.github.io/react-yamps-polygons/

Открываете ссылку, выбираете Канаду, а затем зумин и зумаут. 

Я до этого делал небольшие полигоны с помощью апи я.карт без реакта - проблем не было, а тут они как будто бы перерисовываются (накладываются) - opacity визуально меняется при зуме. Есть ощущение, что как будто бы накладывается второй такой же оверлей и все становится темнее. Пробовал убирать картинки и ставить обычную заливку - то же самое.
![Иллюстрация](https://sun9-32.userapi.com/impf/JBDYOk138c7o6H_yJSM-4Txp7ySShtfNXXXLmA/KBXIC5UwNJc.jpg?size=824x564&quality=96&sign=401da360bd3cc0c7c2e48120c7463dec&type=album)

**Comment by mmarkelov** [comment]
@bramov привет! А для использования чистых апи карт без реакта работает корректно? Посмотрел, но не смог найти где может `react-yandex-maps` ломать отображение

**Comment by bramov** [comment]
@mmarkelov спасибо за такой быстрый фидбек)
Да, похоже все-таки дело в самих картах - https://codepen.io/bramov/pen/eYBxyaV
Спасибо за помощь, ишку, наверное, можно закрывать
