### ISSUE TITLE
Не работают Панорамы

### ISSUE THREAD

**Issue by DieL89** [gribnoysup/react-yandex-maps#298]
Компонент TypeSelector. Выбираю Панорамы. Кликаю на воздушный шар. Выдаёт 2 ошибки:
- panorama.Manager: failed to open air panorama
- Failed to load resource: the server responded with a status of 403 (Forbidden)
В примере из документации поведение аналогичное: https://react-yandex-maps.now.sh/controls/type-selector

Компонент Panorama - пустой див:
https://react-yandex-maps.now.sh/panorama

**Comment by mmarkelov** [comment]
@DieL89 пример корректно работал год назад. Сейчас для использования некоторых модулей вроде маршрутизации и построения маршрутов у вас должен быть ключ разработчика

**Comment by Jeurei** [comment]
> @DieL89 пример корректно работал год назад. Сейчас для использования некоторых модулей вроде маршрутизации и построения панорам у вас должен быть ключ разработчика

 А где нужно прописывать ключ? Не могу найти пример в документации

**Comment by Jeurei** [comment]
@mmarkelov можно где то посмотреть пример подключения? У меня самого выдает ошибку 
<img width="959" alt="изображение" src="https://user-images.githubusercontent.com/56633996/111120380-15597800-858d-11eb-95b5-3c4cea99557e.png">

**Comment by mmarkelov** [comment]
@Jeurei должно быть окей так:
```js
<YMaps query={{ apikey: 'your key' }}>
  <Panorama defaultPoint={[55.733685, 37.588264]} />
</YMaps>
```

**Comment by mmarkelov** [comment]
@Jeurei но ваша ошибка возможно связана что вы не добавили модуль. Без кода сложно сказать точно

**Comment by Jeurei** [comment]
@mmarkelov Если у меня приложение обернуто в YMaps мне нужно для панорамы еще одну обертку создавать в компоненте? Ваш пример работает, просто не думал что надо доп обертку для панорамы

**Comment by mmarkelov** [comment]
@Jeurei не уверен что понял вас. Вы можете в рутовом **YMaps** добавить ключ - тогда все должно быть ок

**Comment by Jeurei** [comment]
@mmarkelov и вправду спасибо огромное
