### ISSUE TITLE
Нельзя получить к объекту из провайдера

### ISSUE THREAD

**Issue by eden-lane** [gribnoysup/react-yandex-maps#303]
Нужна возможность получить доступ к экземпляру `YMaps`. Это нужно для того что бы сделать свой компонент Suggest без использования карты

**Comment by eden-lane** [comment]
Уже есть PR на это #295

**Comment by mmarkelov** [comment]
@eden-lane вы можете использовать **withYMaps**. Советую посмотреть https://github.com/gribnoysup/react-yandex-maps/issues/281 там есть пример использования

**Comment by eden-lane** [comment]
Спасибо за быстрый ответ и рабочее решение!
Однако, будет здорово если когда-нибудь в будущем помимо решения с HOC будет ещё и вариант на хуках - предлагаю не закрывать эту задачу (но решать вам, конечно)

**Comment by mmarkelov** [comment]
@eden-lane закрою, так как уже есть открытый ишью на добавление хуков #264
