### ISSUE TITLE
BalloonContent

### ISSUE THREAD

**Issue by diazdressk** [gribnoysup/react-yandex-maps#309]
Привет. Помогите, пожалуйста! В balloonContent нужно сделать кнопку и навесить на неё действия, как можно сделать?
пытаюсь делать так: 
```js
                   properties={{
                      balloonContent:
                        `<button ${() => console.log(adr.name_ru)}>
                        показать адрес
                        </button>`,
                    }}
```

**Comment by diazdressk** [comment]
https://codesandbox.io/s/focused-joliot-xzesw?file=/src/App.js

**Comment by mmarkelov** [comment]
@diazdressk уже были подобные вопросы:

https://github.com/gribnoysup/react-yandex-maps/issues/208
https://github.com/gribnoysup/react-yandex-maps/issues/226
https://github.com/gribnoysup/react-yandex-maps/issues/255

**Comment by diazdressk** [comment]
Спасибо большое! Разобрался, помогли!
