### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by Dictory** [gribnoysup/react-yandex-maps#32]
onUnmount component error:
`Cannot read property 'remove' of undefined`
in [Control.js#L99](https://github.com/gribnoysup/react-yandex-maps/blob/master/src/Control.js#L99)

**Comment by gribnoysup** [comment]
Thanks for noticing! I really should start thinking how to add tests to the library, it becomes a little bit difficult to add new features without regression 😓 

I'll try to fix this ASAP!

**Comment by gribnoysup** [comment]
Should be fixed in `2.1.2`. Could you check, please?

**Comment by Dictory** [comment]
@gribnoysup thank you. Well job.
