### ISSUE TITLE
Map`s methods

### ISSUE THREAD

**Issue by Dictory** [gribnoysup/react-yandex-maps#34]
Hello, how I can use [methods](https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/Map-docpage/#methods-summary)?

**Comment by gribnoysup** [comment]
Hi @Dictory 

You can use `instanceRef` prop to get to the Map instance:

```jsx
<Map 
  state={{ center: [55.73, 37.75], zoom: 10 }} 
  instanceRef={ref => {
    const center = ref.getCenter();
    console.log(center) // -> [55.73, 37.75]
  }}
/>
```

Be aware that using methods that change map instance state (`setBounds, setCenter, setType` etc.) could desync your map and your app state if your map is controlled from outside:

```jsx
class App extends React.Component {
  state = { zoom: 10 };

  render() {
    return (
      <Map 
        state={{ center: [55.73, 37.75], zoom: this.state.zoom }} 
        instanceRef={ref => {
          ref.setZoom(5);
          console.log(ref.getZoom(), this.state.zoom) // -> 5 10
        }}
      />
    )
  }
}
```

**Comment by Dictory** [comment]
Oh, ok, thanks. I missed it.

**Comment by Dictory** [comment]
Думаю, надо добавить пример в доку. Сам метод я видел, но упустил из внимания.

**Comment by gribnoysup** [comment]
Я все пытаюсь найти время переписать доку, обязательно займусь, как время будет :)
