### ISSUE TITLE
Элементы на карте

### ISSUE THREAD

**Issue by Dictory** [gribnoysup/react-yandex-maps#35]
Пытаюсь показать элемент поверх карты:
```javascript
<YMaps>
  <div id="map-basics">
    <div style={{}} />
    <Map>
      ...
    </Map>
  </div>
</YMaps>
```

Карта не подзагружается.

**Comment by gribnoysup** [comment]
А есть какие-нибудь ошибки? Я не уверен, что проблема в библиотеке. Я сделал такую демку и там все ок: https://codesandbox.io/s/k06koqpn07

```jsx
import React from "react";
import { render } from "react-dom";

import { YMaps, Map } from "react-yandex-maps";

class MapBasics extends React.Component {
  render() {
    return (
      <YMaps>
        <div
          id="map-basics"
          style={{ position: "relative", display: "inline-block" }}
        >
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              backgroundColor: "rgba(0, 0, 0, .8)",
              zIndex: 999
            }}
          />
          <Map state={{ center: [55.76, 37.64], zoom: 10 }} />
        </div>
      </YMaps>
    );
  }
}

render(<MapBasics />, document.getElementById("root"));
```

**Comment by Dictory** [comment]
Все оказалось просто:
`<Map width="100%" height="100%" />`
не работает =) 

Извиняюсь за вопрос. Спасибо за помощь.

**Comment by Dictory** [comment]
Поторопился. Такой оверлэй пропадает есть открыть карту на полный экран. Есть какой-то способ отображать оверлэй и в этом случае?

**Comment by gribnoysup** [comment]
Такой код работает корректно:

```jsx
<Map width="100%" height="100%" />
```

Я обновил [демо](https://codesandbox.io/s/k06koqpn07) и в нем видно, что карты занимают 100% ширины и высоты своего родителя. Скорее всего у тебя что-то не так со стилями.

> Такой оверлэй пропадает есть открыть карту на полный экран. Есть какой-то способ отображать оверлэй и в этом случае?

Когда карты открываются в полноэкранном режиме, они переносятся из контейнера в котором они находятся в `<body />`, это не поведение моей библиотеки, так ведут себя яндекс-карты. Скорее всего в полноэкранном режиме они просто перекрывают твой оверлей

**Comment by Dictory** [comment]
> Когда карты открываются в полноэкранном режиме, они переносятся из контейнера в котором они находятся в <body />, это не поведение моей библиотеки, так ведут себя яндекс-карты. Скорее всего в полноэкранном режиме они просто перекрывают твой оверлей

Да это действительно так, вопрос как все-таки наложить элемент поверх.
Я выкрутился так: убрал контроллер полноэкранного режима и прикрутил свой, который открывает модалку на полный экран.

**Comment by gribnoysup** [comment]
@Dictory Я не разработчик Яндекс Карт, поэтому не могу сказать как это сделать грамотно с точки зрения их API :)

Я думаю по отношению к моей библиотеке это issue можно закрывать, если тебе кажется что что-то всё еще не так, можешь переоткрыть или создать новое
