### ISSUE TITLE
Поведение instanceRef в нарастающем цикле

### ISSUE THREAD

**Issue by dshster** [gribnoysup/react-yandex-maps#36]
Если добавлять элементы по нарастающей, то instanceRef ссылается только на последний элемент, когда как ref — на каждый. Из-за этого невозможно получить ссылку на каждый элемент, если они добавлялись по нарастающей.

Пример, вывод в консоле, нажимаем на + над картой:
https://codesandbox.io/s/mzqx6y52m9

**Comment by gribnoysup** [comment]
`instanceRef` ведет себя как `ref` с функцией, ссылка на которую не меняется, я пока не уверен, что хочу менять это поведение

**Comment by dshster** [comment]
Но сейчас различное поведение instanceRef и ref.  При перерендеринге с добавлением нового объекта instanceRef вызывается только для нового объекта, когда как ref для всех.

**Comment by dshster** [comment]
Решил сохранять инстансы в отдельном объекте: https://codesandbox.io/s/j32q346mpy

**Comment by gribnoysup** [comment]
@dshster я сделал демо, в котором видно, что если ссылка на функцию `ref` не меняется, то ведет она себя так же, как `instanceRef`:

https://codesandbox.io/s/4q3zkqqoy0

Подробнее почему `ref` так себя ведет с функциями, которые создаются прямо в `render` методах можно почитать тут: https://reactjs.org/docs/refs-and-the-dom.html#caveats

Возможно в будущем я поменяю это поведение так, что бы оно точно совпадало с React-ом, пока нет таких планов, есть пара других вещей, которые я хочу добавить в первую очередь
