### ISSUE TITLE
Карта не рендерится сразу

### ISSUE THREAD

**Issue by olgadolg** [gribnoysup/react-yandex-maps#37]
`<YMaps>
    <Map  state={ { center: [55.76, 37.64], zoom: 10 } }>
    </Map>
</YMaps>`

Сама карта рендерится только после каких-либо изменений. (когда компонент апдейтится). Кто-нибудь знает почему такое может происходить?

**Comment by gribnoysup** [comment]
@olgadolg привет! 

Нужно больше деталей. Можешь сделать демо на https://codesandbox.io/ с примером?

**Comment by droganov** [comment]
create react app, подключаем пример
```
import { YMaps, Map } from 'react-yandex-maps';

const App = () => (
  <YMaps>
    <div>
      My awesome application with maps!
      <Map defaultState={{ center: [55.75, 37.57], zoom: 9 }} />
    </div>
  </YMaps>
);
```

получаем вот это:

![image](https://user-images.githubusercontent.com/1375299/46426625-c9614280-c747-11e8-8f61-454fe723d216.png)

**Comment by mmarkelov** [comment]
@droganov странно, все работает в [песочнице](https://codesandbox.io/s/4zx4o488w7)

**Comment by gribnoysup** [comment]
@droganov пожалуйста, открой новое issue. Это issue было открыто для другой версии библиотеки и не может быть таким же как у тебя 

Это issue будет закрыто как устаревшее

**Comment by zogreptile** [comment]
@droganov Нашли решение? У меня карта не отрисовывается только после сборки в create-react-app.

**Comment by droganov** [comment]
@zogreptile да, используем лифлет
@gribnoysup прошу прощения, пропустил ответ, может быть @zogreptile у меня сейчас нет уже той песочницы
