### ISSUE TITLE
react-starter-kit server side rendering ListBox error

### ISSUE THREAD

**Issue by mmarkelov** [gribnoysup/react-yandex-maps#39]
Добрый вечер! Использую react-starter-kit [https://github.com/kriasoft/react-starter-kit](url) для приложения. При добавлении тэга ListBox в консоле вываливаются ошибки, вида 
`Uncaught Error: Unable to find element with ID 1698.
    at invariant (invariant.js:42)
    at precacheChildNodes (ReactDOMComponentTree.js:101)
    at Object.getClosestInstanceFromNode (ReactDOMComponentTree.js:133)
    at handleTopLevelImpl (ReactEventListener.js:56)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:141)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.batchedUpdates (ReactUpdates.js:95)
    at dispatchEvent (ReactEventListener.js:145)
invariant @ invariant.js:42
precacheChildNodes @ ReactDOMComponentTree.js:101
getClosestInstanceFromNode @ ReactDOMComponentTree.js:133
handleTopLevelImpl @ ReactEventListener.js:56
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
`
Пытаясь разобраться в чем дело, рассматривал различные варианты. При отключении функции server side rendering, все нормально. Полагаю, что проблема с этим элементом, ибо только при его использовании появляются ошибки данного вида.

Спасибо!

**Comment by gribnoysup** [comment]
@mmarkelov привет, попробую разобраться

**Comment by mmarkelov** [comment]
@gribnoysup я как понял, такого рода ошибки обычно возникают когда нарушена иерархия тэгов(возможно где-то есть не закрывающийся), проверял в своем проекте вроде все с этим было нормально. Попробую еще покапать на выходных

**Comment by gribnoysup** [comment]
Closed due to inactivity
