### ISSUE TITLE
How to get Yandex Maps API

### ISSUE THREAD

**Issue by sergei-zelinsky** [gribnoysup/react-yandex-maps#4]
Hi there.
How to get Yandex Maps API without rendering Map component.

**Comment by gribnoysup** [comment]
Hi @sergei-zelinsky, sorry for the delay.

Util function that loads api to component is located here https://github.com/gribnoysup/react-yandex-maps/blob/master/src/util/api.js, but it is not possible to import it from this library separately. 

Could you please specify use-case for this scenario, why would you need to have api avaliable without rendering Map component?

**Comment by sergei-zelinsky** [comment]
Hi @gribnoysup.

For example to use static functions of maps API. In my use-case I need to get a route using `route` static function (see [docs for route](https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/route-docpage/)).

**Comment by gribnoysup** [comment]
Okay, this is a good point, I totally overlooked this part of maps api. I'm not sure that this will be easy to implement right now, but I'll see what I can do

**Comment by sergei-zelinsky** [comment]
Great!
Thank you for your answer @gribnoysup.

**Comment by gribnoysup** [comment]
@sergei-zelinsky I'm working on a new version that will allow this behavior, you can track progress here https://github.com/gribnoysup/react-yandex-maps/pull/5

**Comment by gribnoysup** [comment]
1.0.0 is now released, so I'm closing the issue

**Comment by sergei-zelinsky** [comment]
@gribnoysup, thank you for your work.
I suppose you are going to continue work on this library, because it is very useful.
