### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by grozamagustov** [gribnoysup/react-yandex-maps#42]
Привет. Не подскажешь как сделать получение местоположение пользователя? Я так понял надо использовать <GeolocationControl /> только не могу разобраться как с помощью него получить в каком городе находится пользователь. Например выводить в консоли название его города.

**Comment by mmarkelov** [comment]
Заранее извиняюсь если ответ не является оптимальным, можно воспользоваться функцией компонента YMaps onApiAvaliable 
`<YMaps onApiAvaliable={ymaps => this.handleApiAvaliable(ymaps)}>`
Сама функция, в ней можно будет прокинуть результат в state, если потребуется 
`handleApiAvaliable = ymaps => {
    const geolocation = getGeoLocation(ymaps);
  };`
Ну и сама функция получения города в консоле, возможно велосипед - смотрел примеры на Яндексе: [https://tech.yandex.ru/maps/jsbox/2.1/event_reverse_geocode](url)
`function getGeoLocation (ymaps) {
	return ymaps.geolocation.get({
		provider: 'yandex',
		mapStateAutoApply: true
	}).then( result =>
		ymaps.geocode(result.geoObjects.position).then( res => {
			let firstGeoObject = res.geoObjects.get(0);
			console.log(firstGeoObject.getLocalities().length ? firstGeoObject.getLocalities() : firstGeoObject.getAdministrativeAreas())
		})
	);
}`
Ну и после этих действий в консоле появится город пользователя. Возможно я далеко не совсем прав)

**Comment by grozamagustov** [comment]
Спасибо, попробую

**Comment by grozamagustov** [comment]
Огромное вам спасибо, все работает. Тему закрываю)
