### ISSUE TITLE
как тут сделать myMap.behaviors.disable('scrollZoom')

### ISSUE THREAD

**Issue by gloompi** [gribnoysup/react-yandex-maps#46]
как тут сделать myMap.behaviors.disable('scrollZoom')

**Comment by mmarkelov** [comment]
Был уже подобного рода вопрос
https://github.com/gribnoysup/react-yandex-maps/issues/6
Behaviors часть map state
Можете попробовать так
`state={{
        center: center,
        zoom: zoom,
        behaviors: [/* enabled behaviours */]
    }}`
Хотя возможно сейчас уже другой вариант имеется

**Comment by gloompi** [comment]
спасибо)

**Comment by gribnoysup** [comment]
@gloompi привет! Извиняюсь за долгий ответ

С помощью `state`, как @mmarkelov предлагает выше, не получится что-то выключить, только включить. Можешь использовать `instanceRef` для выключения:

```jsx
<Map instanceRef={ref => { ref && ref.behaviors.disable('scrollZoom'); }} />
```

Закрой, пожалуйста, issue, если какой-то из предложенных вариантов решает твою проблему 😉

**Comment by gloompi** [comment]
@gribnoysup Привет, спасибо большое, получилось))

**Comment by FeeLeD** [comment]
state={{ center: center, zoom: zoom, behaviors: behaviors: ["disable('scrollZoom')"] }}

**Comment by kozlovtseva** [comment]
> state={{ center: center, zoom: zoom, behaviors: ["disable('scrollZoom')"] }}

единственное решение для TS. спасибо!!!

**Comment by relaxdd** [comment]
> state={{ center: center, zoom: zoom, behaviors: ["disable('scrollZoom')"] }}

thank you very much, it's helped me
