### ISSUE TITLE
Предложение дополнить доку примерами по работе с объектом map

### ISSUE THREAD

**Issue by mmarkelov** [gribnoysup/react-yandex-maps#48]
Довольно частая ситуация, связанная с тем что нужно использовать instanceRef, для того чтобы использовать map. В Readme достаточно сложно соориентироваться по его использованию, т.е. сказано что мы можем его использовать, но вот примеров нет. Мне кажется, добавление пары примеров сняло достаточное количество вопросов

**Comment by gribnoysup** [comment]
@mmarkelov у меня сейчас нет времени на документацию, к сожалению, я работаю над новой мажорной версией. Я согласен что это хорошая идея, PRs are welcome 😉

**Comment by Brozish** [comment]
@mmarkelov реализовал тестовое задание - использую `instanceRef` в компоненте `MapRoute` для `SearchControl` (получаю координаты и описание по событию `onResultShow`) и `Placemark` (реагирую на `onDragEnd` для получения `ReverseGeocoder` по координатам). Думаю, как пример, кому-то будет полезен
[https://github.com/Brozish/FunBox](url)

**Comment by gribnoysup** [comment]
Closing in favour of #76
