### ISSUE TITLE
Не работает onClick на <Placemark>

### ISSUE THREAD

**Issue by Ivan-Korolenko** [gribnoysup/react-yandex-maps#49]
Создал с помощью библиотеки следующий компонент:

```
import React, { Component } from "react";
import { YMaps, Map as YandexMap, Placemark } from 'react-yandex-maps';

class Map extends Component {

render() {
const { mapPoints } = this.props
const mapCenter = [ mapPoints[0].lat, mapPoints[0].lng ]
const mapState = { center: mapCenter, zoom: 11 }

return (
      <YMaps>
        <YandexMap state={mapState} width={'100%'} height={'100%'}>
        {
          mapPoints.map( (item, key) => (
             <Placemark
                key={key}
                geometry={{
                  type: "Point",
                  coordinates: [ parseFloat(item.lat), parseFloat(item.lng) ],
                }}
                properties={{
                  // Проставляем цифры иконкам на карте
                  iconContent: key+1,
                  hintContent: 'Собственный значок метки',
                  balloonContent: 'Это красивая метка',
                }}
                options={{
                  iconShape: {
                    type: 'Point',
                    coordinates: [ parseFloat(item.lat), parseFloat(item.lng) ]
                  }
                }}
                onClick={function(){ console.log('Got clicked!') }}
              />
          ))
        } 
        </YandexMap>
      </YMaps>
    )
}
}
```

Карта отображается, точки отображаются, но клик по точкам ничего не дает. Если повесить onClick на `<YandexMap/>`, то клик на нее срабатывает, но мне нужен именно клик по `<Placemark/>`.

**Comment by Ivan-Korolenko** [comment]
И балуны тоже не отображаются при клике по `<Placemark/>` на карте.

**Comment by Fantomhaiv** [comment]
Используйте стрелочную функцию `onClick={() => {console.log('It's work for me')}}`

**Comment by Ivan-Korolenko** [comment]
@Fantomhaiv Попробовал. К сожалению, не сработало. Да и дело явно не в функции, потому что та же самая функция работает, если повесить её на `<YandexMap/>`. Да и замена обычной функции на стрелочную могла бы помочь только если бы я использовал внутри нее this или еще что-то, что корректнее работает именно в стрелочных функциях.

**Comment by Fantomhaiv** [comment]
В моем проекте `onClick` корректно работает, вот пример https://codesandbox.io/embed/qkno815m0j

**Comment by Ivan-Korolenko** [comment]
@Fantomhaiv Спасибо! Понял, что проблема в моем проекте. Уже нашел её и исправил. Оказалось, что с данной библиотекой она не связана.
