### ISSUE TITLE
Как триггерить event?

### ISSUE THREAD

**Issue by Ivan-Korolenko** [gribnoysup/react-yandex-maps#50]
Не могу разобраться, как с помощью этой библиотеки вызывать `event` клика на `Placemark` из компонента вне карты. Как я понял, нужно использовать `instanceRef`, но не могу понять, где прописывать подобие вот такой конструкции и как оно должно выглядеть в терминах этой библиотеки (пример с использованием Yandex API) относительно `Placemark`:
`YMaps.Events.notify(placemark, placemark.Events.Click)`

**Comment by mmarkelov** [comment]
@Ivan-Korolenko передаем в ref ссылку на гео объект <Placemark  instanceRef={ref => {  this.ref = ref; }} /> и теперь там где Вам надо вызвать событие используете ее, что-то типа такого:
onClick={() => this.ref.events.fire('click', {target: this.ref})} - тригеррит событие клика, 
YMaps.Events.notify(placemark, placemark.Events.Click) - в новых версиях заменен на fire

**Comment by Ivan-Korolenko** [comment]
Спасибо, сработало.
