### ISSUE TITLE
SuggestView in react-yandex-maps

### ISSUE THREAD

**Issue by deivoff** [gribnoysup/react-yandex-maps#51]
Is it possible to realize SuggestView in React?
I trying connect this function with my input id='suggest' but it's doesn't work for me

```
onApiAvaliable(ymaps) {
ymaps.load(() => {
      const suggestView = ymaps.SuggestView("suggest", {
        results: 10,
      });
}

  render() {
    return (
      <div className="panel panel-default" >
        <div className="panel-heading" >
          <h3 className="panel-title" >My blahblahblah</h3 >
        </div >
        <div className="panel-body">
          <form className="form-horizontal form-border" id="form" >
            <div className="form-group" >
              <label className="col-sm-3 control-label" >Project name</label >
              <div className="col-sm-6" >
                <input
                  type="text"
                  className="form-control"
                  id="suggest"
                />
              </div >
            </div >
          </form>
          <YMaps onApiAvaliable={ymaps => this.onApiAvaliable(ymaps)}> 
...
```

**Comment by mmarkelov** [comment]
@deivoff You just need to create object with new keyword 
```javascript
const suggestView = new ymaps.SuggestView("suggest", {
        results: 10,
      });
```

**Comment by deivoff** [comment]
Thanks it's work for me!

**Comment by deivoff** [comment]
@mmarkelov Thanks it's work for me!

**Comment by razhihan11** [comment]
I can’t figure it out, you can publish the full component code 

> Можно ли реализовать SuggestView в React?
> Я пытаюсь соединить эту функцию с моим вводом id = 'предложить', но это не работает для меня
> 
> ```
> onApiAvaliable(ymaps) {
> ymaps.load(() => {
>       const suggestView = ymaps.SuggestView("suggest", {
>         results: 10,
>       });
> }
> 
>   render() {
>     return (
>       <div className="panel panel-default" >
>         <div className="panel-heading" >
>           <h3 className="panel-title" >My blahblahblah</h3 >
>         </div >
>         <div className="panel-body">
>           <form className="form-horizontal form-border" id="form" >
>             <div className="form-group" >
>               <label className="col-sm-3 control-label" >Project name</label >
>               <div className="col-sm-6" >
>                 <input
>                   type="text"
>                   className="form-control"
>                   id="suggest"
>                 />
>               </div >
>             </div >
>           </form>
>           <YMaps onApiAvaliable={ymaps => this.onApiAvaliable(ymaps)}> 
> ...
> ```
