### ISSUE TITLE
Как получить оригинальный апи или поменять курсор? 

### ISSUE THREAD

**Issue by innot667** [gribnoysup/react-yandex-maps#57]
Нужно поменять курсор.
В оригинальном апи это делается так:
```
map.cursors.push('arrow');
```
https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/util.cursor.Manager-docpage/

В вашей версии я не нашел реализации.
Костыльно оригинальный апи можно получить через события. Например

```
<Map
... onClick={this.handleClick}
>
...
handleClick(e){
        let arCoord = e.get('coords');
        // e.originalEvent.target.cursors.push('arrow');
        return false;
    }
```
Можно ли это сделать через ref или иным образом?

**Comment by gribnoysup** [comment]
Как получить ref описано в документации: https://github.com/gribnoysup/react-yandex-maps#the-instanceref-callback-attribute
