### ISSUE TITLE
Предложение, добавить второй параметр position.

### ISSUE THREAD

**Issue by OlegE90** [gribnoysup/react-yandex-maps#58]
https://github.com/gribnoysup/react-yandex-maps/blob/113afa532dd1ead7b2fa0dc22b085c660a57102c/src/Control.js#L43

**Comment by gribnoysup** [comment]
Второй аргумент метода `add` это `options`: https://tech.yandex.com/maps/doc/jsapi/2.1/ref/reference/control.Manager-docpage/#add

`options` можно передавать через `props` для всех компонентов, в том числе и для Control-ов:

```jsx
<Button options={{ float: 'right' }} />
```
