### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by awakentwice** [gribnoysup/react-yandex-maps#59]
Столкнулся сегодня с проблемой, в консоли ошибка ```Uncaught (in promise) {status: "error", code: 403, message: "Invalid API key"}```
На демо-стенде с компонентом та же песня

**Comment by gribnoysup** [comment]
Без примера не очень понятно о чем речь. Какой API key? Какой демо-стенд? Небольшое изолированное демо очень поможет понять в чем проблема. Можно сделать такое на https://codesandbox.io/ например

**Comment by awakentwice** [comment]
Проблема оказалась местечковой
Извините за беспокойство

**Comment by Hydrock** [comment]
@awakentwice как решили? у меня тоже самое

**Comment by Egor18032019** [comment]
> 
> 
> @awakentwice как решили? у меня тоже самое

такая же беда

**Comment by Egor18032019** [comment]
нужно ключ передать:
 <YMaps
        enterprise
        query={{
          apikey: `ключик с кабинета разработчика`,
        }}>
