### ISSUE TITLE
features в ObjectManager не обновляются

### ISSUE THREAD

**Issue by Vusluk** [gribnoysup/react-yandex-maps#62]
Вернее обновление features касается только добавления/удаления объектов. 
Ситуация следующая: юзер открывает баллун, в нем кнопка, при клике на неё меняется properties у  геоОбъекта и это изменение не попадает в objectManager.

**Comment by gribnoysup** [comment]
Hi @Vusluk! 

Yep, can confirm that this issue exists. This one would be tricky to solve, though. As a workaround, you could probably modify your GeoObject straight from the click event on the button 🤔

**Comment by gribnoysup** [comment]
@Vusluk the issue should be fixed in `v2.2.0`
