### ISSUE TITLE
Поддержка для Typescript 

### ISSUE THREAD

**Issue by Lurkomorie** [gribnoysup/react-yandex-maps#63]
Нету поддержки написания на Typescript? Нету declaration файла

**Comment by gribnoysup** [comment]
There is no TypeScript support, sorry. PRs are welcome 😸

**Comment by zalishchuk** [comment]
I am currently working on TypeScript typings for `react-yandex-maps`, but I need some help with reviewing components types and also need `prop-types` for `controls` components because they are missing.
