### ISSUE TITLE
react native support

### ISSUE THREAD

**Issue by alpamys-qanybet** [gribnoysup/react-yandex-maps#65]
Будет ли поддержка React Native?

**Comment by gribnoysup** [comment]
@alpamys-qanybet привет! Не уверен что текущая реализация этой библиотеки позволит использовать её в react-native. У меня не достаточно опыта с RN что бы точно ответить на этот вопрос, к сожалению. Я закрою issue, но обязательно пингану тебя, если что-то изменится
