### ISSUE TITLE
Get API instance without rendering YMaps

### ISSUE THREAD

**Issue by hastom** [gribnoysup/react-yandex-maps#66]
I want to use routes API to calculate a route length between two point. Can i access API without rendering YMaps component?

**Comment by mmarkelov** [comment]
@hastom you can import **YMaps** component, that just make yandex API available  for you. And then you can use **onApiAvaliable** method, like [this](https://codesandbox.io/s/mqqz3r0w3j)

**Comment by hastom** [comment]
@mmarkelov thanks, that helps
