### ISSUE TITLE
Можно ли строить маршруты? И как растянуть в слое 100% по ширине и высоте? 

### ISSUE THREAD

**Issue by xfishernet** [gribnoysup/react-yandex-maps#68]
Можно ли строить маршруты? И как растянуть в слое 100% по ширине и высоте? Нашел размеры только в пикселах, а по построению маршрута вообще ничего не нашел.

**Comment by mmarkelov** [comment]
@xfishernet строить маршруты можно, используя инстанс карты и функцию **onApiAvaliable**.
Подробнее здесь #14 
Перенес этот пример [сюда](https://codesandbox.io/s/lrwyz2z4l9)

**Comment by xfishernet** [comment]
Спасибо за быстрый ответ, да, маршруты отлично работают, а вот с растягиванием карты на весь экран проблемка: https://codesandbox.io/s/mo0945ko99

**Comment by xfishernet** [comment]
Если ширину задаю то всё ок:

 <Map state={mapState}  width="100%"...

но если добавляю height="100%" или любое другое число, то в height становится 0, если посмотреть в браузере...

**Comment by mmarkelov** [comment]
@xfishernet вроде же норм https://codesandbox.io/s/p37m4lz4j7

**Comment by xfishernet** [comment]
да, всё ок, спс. Кстати, еще вопрос про маршруты, а как можно их динамически добавлять на карту и убирать? По событие загрузки карты то понятно, а вот как дальше влиять на карту не понятно из официальных примеров.

**Comment by mmarkelov** [comment]
@xfishernet Обновил песочницу. https://codesandbox.io/s/p37m4lz4j7

**Comment by xfishernet** [comment]
а в виде компонентов нельзя строить маршруты? по типу <Placemark /> ...

**Comment by mmarkelov** [comment]
@xfishernet в виде компонентов нет, автор говорил, что вряд ли будет добавлять API для роутов.
Подробнее здесь #15 
Но можете расширить имеющийся функционал. Добавление роутов здесь
https://github.com/gribnoysup/react-yandex-maps/pull/17/files

**Comment by gribnoysup** [comment]
@mmarkelov огромное спасибо за помощь с issues в этом репозитории! У меня, к сожалению, не так много времени на них остается, обычно к моменту когда я могу ответить, ты уже дал правильный ответ на вопрос ;)

@xfishernet @mmarkelov скорее всего будет поддержка для этого АПИ в виде компонентов, с исключением для `multiRoute`, это то, что я имел в виду в том issue. Главный фокус у меня сейчас на большом апдейте для библиотеки в целом, новые библиотечные АПИ позволят делать такие интеграции намного проще со стороны пользователей библиотеки. К сожалению я не могу даже приблизительно сказать пока, когда релиз будет доступен

**Comment by xfishernet** [comment]
А как можно словить событие из компоненты Map, когда this.map доступна уже? -> 

instanceRef={ref => (this.map = ref)

**Comment by gribnoysup** [comment]
`instanceRef` должно быть достаточно для этого

**Comment by xfishernet** [comment]
точно, спс ))
