### ISSUE TITLE
Select location

### ISSUE THREAD

**Issue by Yar-R** [gribnoysup/react-yandex-maps#69]
add support of location selection

**Comment by gribnoysup** [comment]
Hi @Yar-R! I'm not quite sure what you are talking about. Is it about Yandex.Maps API language? In that case you can use [`query.lang`](https://tech.yandex.com/maps/doc/jsapi/2.1/dg/concepts/load-docpage/#param) parameter on the `<YMaps />` component to switch the language. Here is an example that will mount a Map with an english locale:

```jsx
const App = () => (
  <YMaps query={{ lang: 'en_RU' }}>
    <div>
      An app with an english map:
      <Map />
    </div>
  </YMaps>
)
```

**Comment by gribnoysup** [comment]
@Yar-R All `Yandex.Maps` object events are supported by this library. To get the coordinates on click you can use `onClick` event and a special `.get('coords')` method that is provided with `Yandex.Maps` event object. Here is a small demo:

https://codesandbox.io/s/01nllo2j4w

There is a small event section in the docs of this library: https://github.com/gribnoysup/react-yandex-maps#events
You can learn more about supported events in `Yandex.Maps` form their documentation. Here is a section about `Map` object, for example: https://tech.yandex.com/maps/jsbox/2.1/event_properties

**Comment by Arsennikum** [comment]
Now there is no event section in docs...
