### ISSUE TITLE
Неправильное размещение меток на карте

### ISSUE THREAD

**Issue by goodok21** [gribnoysup/react-yandex-maps#71]
Например, есть координаты для точек:
65.173107, 167.959015
64.681627, 170.406987
65.012088, -175.840402
67.044523, -178.879519

точки с отрицательной долготой отобразятся на проекции карты слева, а те что с положительной долготой - справа.
("слева" и "справа" имеется в виду если сделать минимальный зум карты, то появится больше одной карты Мира и какие-то будут на одной части, а какие то на другой)

В чем может быть проблема?

Небольшой jsFiddle с Яндекс.Картами без использования обертки, на котором отображаются две точки с положительной и отрицательной долготой:
http://jsfiddle.net/awx6gnu8/14/

**Comment by gribnoysup** [comment]
Привет! Я сделал такое же демо с `react-yandex-maps` и вижу такой же результат как в твоем примере без библиотеки: https://codesandbox.io/s/k997z78pkr

Не очень понимаю в чем issue, можешь уточнить?

**Comment by goodok21** [comment]
Я использовал ObjectManager, вот форк:
https://codesandbox.io/s/232jpow110

**Comment by goodok21** [comment]
Неправильную ссылку кинул, вот правильная:
https://codesandbox.io/s/xr21n0x0zw

Если создать массив Features где будут точки с отрицательными координатами, вида:
`let features = [
  {
    geometry: {
      type: "Point",
      coordinates: [64.725236, 177.529702]
    },
    id: 126881,
    type: "Feature"
  },
  ...]`

и использовать компонент `<ObjectManager features={features} />`, то можно увидеть проблему если уменьшить зум.

**Comment by gribnoysup** [comment]
@goodok21 только что попробовал использовать ObjectManager напрямую (форк твоего фиддла: http://jsfiddle.net/q25Lvw49/3/), такое же поведение, выглядит как проблема с Яндекс.Картами, я тут, к сожалению, никак не могу помочь

**Comment by mmarkelov** [comment]
@goodok21 похоже баг карт. Возможно стоит спросить на stackoverflow

**Comment by goodok21** [comment]
@mmarkelov спасибо за совет, задал вопрос там. А вообще есть какие-то идеи по причинам этого и по возможному решению? Ну кроме того, чтобы использовать Placemark вместо ObjectManager

**Comment by gribnoysup** [comment]
Для контекста вопрос с ответом про ObjectManager на StackOverflow: https://ru.stackoverflow.com/questions/858706/yandexmaps-objectmanager-%D0%B8-%D0%BE%D1%82%D1%80%D0%B8%D1%86%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%B4%D0%BE%D0%BB%D0%B3%D0%BE%D1%82%D0%B0
