### ISSUE TITLE
Custom route balloon 

### ISSUE THREAD

**Issue by novpeter** [gribnoysup/react-yandex-maps#72]
Как передать свой react-компонент в routeBalloonContentLayout?

**Comment by mmarkelov** [comment]
@novpeter Функция ymaps.templateLayoutFactory.createClass на основе которой генерятся шаблоны требует на вход строку. Можно попробовать сгенерировать ее с помощью **renderToString** из **'react-dom/server'**. Не пробовал, но должно сработать

**Comment by gribnoysup** [comment]
Closed due to inactivity
