### ISSUE TITLE
Wrong lifehooks initialization (componentWillReceiveProps)

### ISSUE THREAD

**Issue by lfoma** [gribnoysup/react-yandex-maps#73]
Hello! Actually for component Map (m.b. for other components too), on `componentWillReceiveProps` hook, component will mount again instead of update.
That is because of check `instance` property of `state`. At that hook, component have old state, instead updated. Its can be noted from comment to that hook at react sources:
>    // Note: During these life-cycles, instance.props/instance.state are what
>  // ever the previously attempted to render - not the "current". However,
>  // during componentDidUpdate we pass the "current" props.
at `updateClassInstance()`;

By this bug, component will initialize instance twice: once on component mount and then when component will recieve props imidiatly. New instance will replace old, initialized and this will cause bug on `instanceRef`, what be called twice.

**Comment by gribnoysup** [comment]
Hi @lfoma!

Unfortunately, I can't recreate the issue you are encountering, can you create a small reproduction on [codesandbox.io](codesandbox.io)?

**Comment by gribnoysup** [comment]
Those "unsafe" life hooks are not used anymore starting from v3 even if there was a bug is should be gone
