### ISSUE TITLE
Adding a control element RouteButton

### ISSUE THREAD

**Issue by solovenko-v** [gribnoysup/react-yandex-maps#74]
А можно реализовать элемент управления RouteButton, вызывающий панель маршрутизации?
![image](https://user-images.githubusercontent.com/16318589/44096023-e72e6c20-9fe2-11e8-8927-46d6796594a8.png)
Есть RouteEditor, но это не то же самое.

**Comment by mmarkelov** [comment]
@solovenko-v можно. Для этого в стэйт мапа нужно добавить **controls: ['routeButtonControl']**
[Пример](https://codesandbox.io/s/llq5z3v76m)

**Comment by gribnoysup** [comment]
@solovenko-v ответ @mmarkelov правильный, другим способом может быть использовать примитив `<Control />` и задать ему `"RouteButton"` как `type` в `props`, в таком случае ты можешь прокидывать на компонент эвенты, если это требуется. [Пример](https://codesandbox.io/s/vnz3lz1185)

Оставлю это issue открытым, такой компонент можно добавить в библиотеку 👍

**Comment by gribnoysup** [comment]
Теперь такой компонент есть в библиотеке "из коробки"
