### ISSUE TITLE
Panoramic view

### ISSUE THREAD

**Issue by Aruseli** [gribnoysup/react-yandex-maps#81]
How to make a panoramic view only?

**Comment by gribnoysup** [comment]
Hi @Aruseli! Can you specify which maps API are you talking about?

**Comment by mmarkelov** [comment]
@Aruseli You can do something like [this](https://codesandbox.io/s/l9xzkq49mq) to implement panorama

**Comment by Aruseli** [comment]
@mmarkelov great, thank you. That's what I need

**Comment by Aruseli** [comment]
@gribnoysup thank you, @mmarkelov gave me the answer

**Comment by gribnoysup** [comment]
I'll open this one because I think we can add first class support for this API in the library 👍 

@mmarkelov thank you as always! 🎉

**Comment by mmarkelov** [comment]
@Aruseli @gribnoysup I just made example for new **react-yandex-maps**. I think we could make component for Panorama, but I'm not sure if it needed.
[Panorama view v3](https://codesandbox.io/s/5kjpzv0pk)

**Comment by Aruseli** [comment]
@mmarkelov @gribnoysup  That's a good idea. I think this component can be very useful to someone.

**Comment by gribnoysup** [comment]
Released in `v3.1.0`, thanks @mmarkelov 🎉
