### ISSUE TITLE
Add additional info for Start docs server

### ISSUE THREAD

**Issue by mmarkelov** [gribnoysup/react-yandex-maps#87]
When I tried to run **npm run dev** in next branch I got an error **Can't resolve '../../dist/react-yandex-maps'**
So before this I need to run **npm run build** from **src** directory - I think it will be nice to add this step to documentation

**Comment by gribnoysup** [comment]
It is mentioned in the [step 3 of this docs section](https://github.com/gribnoysup/react-yandex-maps/tree/next#developing-locally). I wonder if this is still not clear enough 🤔Do you have a suggestion how to make that clearer? What will work for you, for example?

**Comment by mmarkelov** [comment]
@gribnoysup Sorry, that is my fault - I thought that **npm run dev** will not compile source to dist

**Comment by gribnoysup** [comment]
@mmarkelov made a small change there, hope this section makes more sense now https://github.com/gribnoysup/react-yandex-maps/commit/c93b6e9851e8b25b87b9650dc942e6c30f2e5d68 😅

**Comment by mmarkelov** [comment]
@gribnoysup yeah that is more descriptive as for me. Thanks!!
