### ISSUE TITLE
How to remove Cluster Caption in header?

### ISSUE THREAD

**Issue by AliveDD** [gribnoysup/react-yandex-maps#89]
Hi, how to remove Cluster Caption in balloon header?

![screen shot 2018-08-27 at 18 31 09](https://user-images.githubusercontent.com/5255027/44670575-bada8980-aa2b-11e8-9868-53a316cf9267.png)

if my **balloon content body** and **cluster caption** are same, in right side we have duplicated content

**Comment by gribnoysup** [comment]
Hi @AliveDD! Can you specify which behaviour from Yandex.Maps JS API you are trying to recreate?

**Comment by gribnoysup** [comment]
I went through Yandex maps docs quickly and couldn't find an easy solution with their API. Will keep this issue open if somebody can come up with one 👍

**Comment by gribnoysup** [comment]
Closed due to inactivity

**Comment by alexbom** [comment]
Did somebody find the solution?

**Comment by gulnazkassym** [comment]
`clusterBalloonItemContentLayout: ymaps.templateLayoutFactory.createClass('{{ properties.balloonContentBody|raw }}'),
`
[](http://jsfiddle.net/j9bLv0wy/)
