### ISSUE TITLE
Ошибка при Server side rendering

### ISSUE THREAD

**Issue by koekaverna** [gribnoysup/react-yandex-maps#9]
Добрый день, у меня появляется следующая ошибка при попытке сборки:
```
C:\code\webserver\vrch\node_modules\react-yandex-maps\main\util\api.js:36
    this.api = window[ns] || null;
               ^

ReferenceError: window is not defined
```
При замене строки на 
`this.api = typeof window !== 'undefined' ? (window[ns] || null) : null;`
Всё заработало

**Comment by gribnoysup** [comment]
@koekaverna привет! Спасибо за информацию, я действительно совсем забыл про SSR :sweat: Хочешь сделать пулл-реквест с фиксом?

**Comment by koekaverna** [comment]
Готово.
