### ISSUE TITLE
На Андроиде карты не работают

### ISSUE THREAD

**Issue by GothicWay** [gribnoysup/react-yandex-maps#97]
https://files.slack.com/files-pri/T5J03JCKV-FCKBNHA8Z/image.png
Вот такая ошибка вылазит на андроиде при  #запуске
Проект уже в открытом доступе, с кодом проблема, то что нет времени, в песочницу перенести часть. 
https://полезныйгород.рф

https://cdn1.savepice.ru/uploads/2018/9/6/827dd10418f8d664435c1c2b33263f4f-full.png
ссылка на картинку, сайт как бы не адаптивный, но должен загружаться на мобилка, на айфоне загружается, на андроиде под любым браузером падает

**Comment by mmarkelov** [comment]
@GothicWay нужно побольше информации. А лучше демо в [песочнице](https://codesandbox.io/)
p.s. скриншот с ошибкой было б неплохо выложить на какой-нибудь открытый ресурс, ибо не вариант его посмотреть в слаке

**Comment by GothicWay** [comment]
обновил инфу

**Comment by mmarkelov** [comment]
@GothicWay было б неплохо еще увидеть текст ошибки. Я так предполагаю что нужно делать дополнительную проверку на **null** перед вызовом       https://github.com/gribnoysup/react-yandex-maps/blob/5462b72eec56f07fd5ac559b746dbb9b1ad9903f/src/Map.js#L145

**Comment by gribnoysup** [comment]
@GothicWay @mmarkelov действительно, выглядит как будто компонент обновляется перед тем как API готово, соответственно `instance` еще нет. Сейчас сделаю патч релиз 👍

**Comment by gribnoysup** [comment]
Должно работать в `react-yandex-maps@2.1.6`

@GothicWay можешь проверить и написать как оно?

**Comment by gribnoysup** [comment]
@GothicWay запаблишил с неправильной версией, сорри. Теперь должно быть ок: `react-yandex-maps@2.2.1`

**Comment by GothicWay** [comment]
@mmarkelov текст ошибки как раз что container 'undefined', происходит именно на андроидах, првоерял в хрмое и в родном каком то браузере, кстати воспроизводится в симуляторе

**Comment by GothicWay** [comment]
@gribnoysup спасибо за оперативность, заработало
